/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup TakeOffLocation TakeOffLocation
 * @brief TakeOffLocation setting which contains the destination of a ReturnToBase operation
 *
 * Autogenerated files and functions for TakeOffLocation Object
 * @{ 
 *
 * @file       takeofflocation.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 * @brief      Implementation of the TakeOffLocation object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: takeofflocation.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include <openpilot.h>
#include "takeofflocation.h"

// Private variables
#if (defined(__MACH__) && defined(__APPLE__))
static UAVObjHandle handle __attribute__((section("__DATA,_uavo_handles")));
#else
static UAVObjHandle handle __attribute__((section("_uavo_handles")));
#endif

/**
 * Initialize object.
 * \return 0 Success
 * \return -1 Failure to initialize or -2 for already initialized
 */
int32_t TakeOffLocationInitialize(void)
{
    // Compile time assertion that the TakeOffLocationDataPacked and TakeOffLocationData structs
    // have the same size (though instances of TakeOffLocationData
    // should be placed in memory by the linker/compiler on a 4 byte alignment).
    PIOS_STATIC_ASSERT(sizeof(TakeOffLocationDataPacked) == sizeof(TakeOffLocationData));
    
    // Don't set the handle to null if already registered
    if (UAVObjGetByID(TAKEOFFLOCATION_OBJID)) {
        return -2;
    }

    // Register object with the object manager
    handle = UAVObjRegister(TAKEOFFLOCATION_OBJID,
        TAKEOFFLOCATION_ISSINGLEINST, TAKEOFFLOCATION_ISSETTINGS, TAKEOFFLOCATION_ISPRIORITY, TAKEOFFLOCATION_NUMBYTES, &TakeOffLocationSetDefaults);

    // Done
    return handle ? 0 : -1;
}

/**
 * Initialize object fields and metadata with the default values.
 * If a default value is not specified the object fields
 * will be initialized to zero.
 */
void TakeOffLocationSetDefaults(UAVObjHandle obj, uint16_t instId)
{
    TakeOffLocationData data;

    // Initialize object fields to their default values
    UAVObjGetInstanceData(obj, instId, &data);
    memset(&data, 0, sizeof(TakeOffLocationData));
    data.North = 0.000000e+00f;
    data.East = 0.000000e+00f;
    data.Down = 0.000000e+00f;
    data.Mode = 0;
    data.Status = 1;

    UAVObjSetInstanceData(obj, instId, &data);

    // Initialize object metadata to their default values
    if ( instId == 0 ) {
        UAVObjMetadata metadata;
        metadata.flags =
            ACCESS_READWRITE << UAVOBJ_ACCESS_SHIFT |
            ACCESS_READWRITE << UAVOBJ_GCS_ACCESS_SHIFT |
            1 << UAVOBJ_TELEMETRY_ACKED_SHIFT |
            1 << UAVOBJ_GCS_TELEMETRY_ACKED_SHIFT |
            UPDATEMODE_ONCHANGE << UAVOBJ_TELEMETRY_UPDATE_MODE_SHIFT |
            UPDATEMODE_ONCHANGE << UAVOBJ_GCS_TELEMETRY_UPDATE_MODE_SHIFT |
            UPDATEMODE_MANUAL << UAVOBJ_LOGGING_UPDATE_MODE_SHIFT;
        metadata.telemetryUpdatePeriod = 0;
        metadata.gcsTelemetryUpdatePeriod = 0;
        metadata.loggingUpdatePeriod = 0;
        UAVObjSetMetadata(obj, &metadata);
    }
}

/**
 * Get object handle
 */
UAVObjHandle TakeOffLocationHandle()
{
    return handle;
}

/**
 * Get/Set object Functions
 */
void TakeOffLocationNorthSet(float *NewNorth)
{
    UAVObjSetDataField(TakeOffLocationHandle(), (void *)NewNorth, offsetof(TakeOffLocationData, North), sizeof(float));
}
void TakeOffLocationNorthGet(float *NewNorth)
{
    UAVObjGetDataField(TakeOffLocationHandle(), (void *)NewNorth, offsetof(TakeOffLocationData, North), sizeof(float));
}
void TakeOffLocationEastSet(float *NewEast)
{
    UAVObjSetDataField(TakeOffLocationHandle(), (void *)NewEast, offsetof(TakeOffLocationData, East), sizeof(float));
}
void TakeOffLocationEastGet(float *NewEast)
{
    UAVObjGetDataField(TakeOffLocationHandle(), (void *)NewEast, offsetof(TakeOffLocationData, East), sizeof(float));
}
void TakeOffLocationDownSet(float *NewDown)
{
    UAVObjSetDataField(TakeOffLocationHandle(), (void *)NewDown, offsetof(TakeOffLocationData, Down), sizeof(float));
}
void TakeOffLocationDownGet(float *NewDown)
{
    UAVObjGetDataField(TakeOffLocationHandle(), (void *)NewDown, offsetof(TakeOffLocationData, Down), sizeof(float));
}
void TakeOffLocationModeSet(uint8_t *NewMode)
{
    UAVObjSetDataField(TakeOffLocationHandle(), (void *)NewMode, offsetof(TakeOffLocationData, Mode), sizeof(uint8_t));
}
void TakeOffLocationModeGet(uint8_t *NewMode)
{
    UAVObjGetDataField(TakeOffLocationHandle(), (void *)NewMode, offsetof(TakeOffLocationData, Mode), sizeof(uint8_t));
}
void TakeOffLocationStatusSet(uint8_t *NewStatus)
{
    UAVObjSetDataField(TakeOffLocationHandle(), (void *)NewStatus, offsetof(TakeOffLocationData, Status), sizeof(uint8_t));
}
void TakeOffLocationStatusGet(uint8_t *NewStatus)
{
    UAVObjGetDataField(TakeOffLocationHandle(), (void *)NewStatus, offsetof(TakeOffLocationData, Status), sizeof(uint8_t));
}


/**
 * @}
 */
