/**
 ******************************************************************************
 *
 * @file       debuglogentry.h
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @see        The GNU Public License (GPL) Version 3
 * @addtogroup GCSPlugins GCS Plugins
 * @{
 * @addtogroup UAVObjectsPlugin UAVObjects Plugin
 * @{
 *   
 * @note       Object definition file: debuglogentry.xml. 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @brief      The UAVUObjects GCS plugin 
 *****************************************************************************/
/* 
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 3 of the License, or 
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 * 
 * You should have received a copy of the GNU General Public License along 
 * with this program; if not, write to the Free Software Foundation, Inc., 
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
#ifndef DEBUGLOGENTRY_H
#define DEBUGLOGENTRY_H

#include "uavdataobject.h"
#include "uavobjectmanager.h"

class UAVOBJECTS_EXPORT DebugLogEntry: public UAVDataObject
{
    Q_OBJECT
    Q_PROPERTY(quint32 FlightTime READ getFlightTime WRITE setFlightTime NOTIFY FlightTimeChanged);
    Q_PROPERTY(quint32 ObjectID READ getObjectID WRITE setObjectID NOTIFY ObjectIDChanged);
    Q_PROPERTY(quint16 Flight READ getFlight WRITE setFlight NOTIFY FlightChanged);
    Q_PROPERTY(quint16 Entry READ getEntry WRITE setEntry NOTIFY EntryChanged);
    Q_PROPERTY(quint16 InstanceID READ getInstanceID WRITE setInstanceID NOTIFY InstanceIDChanged);
    Q_PROPERTY(quint16 Size READ getSize WRITE setSize NOTIFY SizeChanged);
    Q_PROPERTY(quint8 Type READ getType WRITE setType NOTIFY TypeChanged);
    Q_PROPERTY(quint8 Data_0 READ getData_0 WRITE setData_0 NOTIFY Data_0Changed);
    Q_PROPERTY(quint8 Data_1 READ getData_1 WRITE setData_1 NOTIFY Data_1Changed);
    Q_PROPERTY(quint8 Data_2 READ getData_2 WRITE setData_2 NOTIFY Data_2Changed);
    Q_PROPERTY(quint8 Data_3 READ getData_3 WRITE setData_3 NOTIFY Data_3Changed);
    Q_PROPERTY(quint8 Data_4 READ getData_4 WRITE setData_4 NOTIFY Data_4Changed);
    Q_PROPERTY(quint8 Data_5 READ getData_5 WRITE setData_5 NOTIFY Data_5Changed);
    Q_PROPERTY(quint8 Data_6 READ getData_6 WRITE setData_6 NOTIFY Data_6Changed);
    Q_PROPERTY(quint8 Data_7 READ getData_7 WRITE setData_7 NOTIFY Data_7Changed);
    Q_PROPERTY(quint8 Data_8 READ getData_8 WRITE setData_8 NOTIFY Data_8Changed);
    Q_PROPERTY(quint8 Data_9 READ getData_9 WRITE setData_9 NOTIFY Data_9Changed);
    Q_PROPERTY(quint8 Data_10 READ getData_10 WRITE setData_10 NOTIFY Data_10Changed);
    Q_PROPERTY(quint8 Data_11 READ getData_11 WRITE setData_11 NOTIFY Data_11Changed);
    Q_PROPERTY(quint8 Data_12 READ getData_12 WRITE setData_12 NOTIFY Data_12Changed);
    Q_PROPERTY(quint8 Data_13 READ getData_13 WRITE setData_13 NOTIFY Data_13Changed);
    Q_PROPERTY(quint8 Data_14 READ getData_14 WRITE setData_14 NOTIFY Data_14Changed);
    Q_PROPERTY(quint8 Data_15 READ getData_15 WRITE setData_15 NOTIFY Data_15Changed);
    Q_PROPERTY(quint8 Data_16 READ getData_16 WRITE setData_16 NOTIFY Data_16Changed);
    Q_PROPERTY(quint8 Data_17 READ getData_17 WRITE setData_17 NOTIFY Data_17Changed);
    Q_PROPERTY(quint8 Data_18 READ getData_18 WRITE setData_18 NOTIFY Data_18Changed);
    Q_PROPERTY(quint8 Data_19 READ getData_19 WRITE setData_19 NOTIFY Data_19Changed);
    Q_PROPERTY(quint8 Data_20 READ getData_20 WRITE setData_20 NOTIFY Data_20Changed);
    Q_PROPERTY(quint8 Data_21 READ getData_21 WRITE setData_21 NOTIFY Data_21Changed);
    Q_PROPERTY(quint8 Data_22 READ getData_22 WRITE setData_22 NOTIFY Data_22Changed);
    Q_PROPERTY(quint8 Data_23 READ getData_23 WRITE setData_23 NOTIFY Data_23Changed);
    Q_PROPERTY(quint8 Data_24 READ getData_24 WRITE setData_24 NOTIFY Data_24Changed);
    Q_PROPERTY(quint8 Data_25 READ getData_25 WRITE setData_25 NOTIFY Data_25Changed);
    Q_PROPERTY(quint8 Data_26 READ getData_26 WRITE setData_26 NOTIFY Data_26Changed);
    Q_PROPERTY(quint8 Data_27 READ getData_27 WRITE setData_27 NOTIFY Data_27Changed);
    Q_PROPERTY(quint8 Data_28 READ getData_28 WRITE setData_28 NOTIFY Data_28Changed);
    Q_PROPERTY(quint8 Data_29 READ getData_29 WRITE setData_29 NOTIFY Data_29Changed);
    Q_PROPERTY(quint8 Data_30 READ getData_30 WRITE setData_30 NOTIFY Data_30Changed);
    Q_PROPERTY(quint8 Data_31 READ getData_31 WRITE setData_31 NOTIFY Data_31Changed);
    Q_PROPERTY(quint8 Data_32 READ getData_32 WRITE setData_32 NOTIFY Data_32Changed);
    Q_PROPERTY(quint8 Data_33 READ getData_33 WRITE setData_33 NOTIFY Data_33Changed);
    Q_PROPERTY(quint8 Data_34 READ getData_34 WRITE setData_34 NOTIFY Data_34Changed);
    Q_PROPERTY(quint8 Data_35 READ getData_35 WRITE setData_35 NOTIFY Data_35Changed);
    Q_PROPERTY(quint8 Data_36 READ getData_36 WRITE setData_36 NOTIFY Data_36Changed);
    Q_PROPERTY(quint8 Data_37 READ getData_37 WRITE setData_37 NOTIFY Data_37Changed);
    Q_PROPERTY(quint8 Data_38 READ getData_38 WRITE setData_38 NOTIFY Data_38Changed);
    Q_PROPERTY(quint8 Data_39 READ getData_39 WRITE setData_39 NOTIFY Data_39Changed);
    Q_PROPERTY(quint8 Data_40 READ getData_40 WRITE setData_40 NOTIFY Data_40Changed);
    Q_PROPERTY(quint8 Data_41 READ getData_41 WRITE setData_41 NOTIFY Data_41Changed);
    Q_PROPERTY(quint8 Data_42 READ getData_42 WRITE setData_42 NOTIFY Data_42Changed);
    Q_PROPERTY(quint8 Data_43 READ getData_43 WRITE setData_43 NOTIFY Data_43Changed);
    Q_PROPERTY(quint8 Data_44 READ getData_44 WRITE setData_44 NOTIFY Data_44Changed);
    Q_PROPERTY(quint8 Data_45 READ getData_45 WRITE setData_45 NOTIFY Data_45Changed);
    Q_PROPERTY(quint8 Data_46 READ getData_46 WRITE setData_46 NOTIFY Data_46Changed);
    Q_PROPERTY(quint8 Data_47 READ getData_47 WRITE setData_47 NOTIFY Data_47Changed);
    Q_PROPERTY(quint8 Data_48 READ getData_48 WRITE setData_48 NOTIFY Data_48Changed);
    Q_PROPERTY(quint8 Data_49 READ getData_49 WRITE setData_49 NOTIFY Data_49Changed);
    Q_PROPERTY(quint8 Data_50 READ getData_50 WRITE setData_50 NOTIFY Data_50Changed);
    Q_PROPERTY(quint8 Data_51 READ getData_51 WRITE setData_51 NOTIFY Data_51Changed);
    Q_PROPERTY(quint8 Data_52 READ getData_52 WRITE setData_52 NOTIFY Data_52Changed);
    Q_PROPERTY(quint8 Data_53 READ getData_53 WRITE setData_53 NOTIFY Data_53Changed);
    Q_PROPERTY(quint8 Data_54 READ getData_54 WRITE setData_54 NOTIFY Data_54Changed);
    Q_PROPERTY(quint8 Data_55 READ getData_55 WRITE setData_55 NOTIFY Data_55Changed);
    Q_PROPERTY(quint8 Data_56 READ getData_56 WRITE setData_56 NOTIFY Data_56Changed);
    Q_PROPERTY(quint8 Data_57 READ getData_57 WRITE setData_57 NOTIFY Data_57Changed);
    Q_PROPERTY(quint8 Data_58 READ getData_58 WRITE setData_58 NOTIFY Data_58Changed);
    Q_PROPERTY(quint8 Data_59 READ getData_59 WRITE setData_59 NOTIFY Data_59Changed);
    Q_PROPERTY(quint8 Data_60 READ getData_60 WRITE setData_60 NOTIFY Data_60Changed);
    Q_PROPERTY(quint8 Data_61 READ getData_61 WRITE setData_61 NOTIFY Data_61Changed);
    Q_PROPERTY(quint8 Data_62 READ getData_62 WRITE setData_62 NOTIFY Data_62Changed);
    Q_PROPERTY(quint8 Data_63 READ getData_63 WRITE setData_63 NOTIFY Data_63Changed);
    Q_PROPERTY(quint8 Data_64 READ getData_64 WRITE setData_64 NOTIFY Data_64Changed);
    Q_PROPERTY(quint8 Data_65 READ getData_65 WRITE setData_65 NOTIFY Data_65Changed);
    Q_PROPERTY(quint8 Data_66 READ getData_66 WRITE setData_66 NOTIFY Data_66Changed);
    Q_PROPERTY(quint8 Data_67 READ getData_67 WRITE setData_67 NOTIFY Data_67Changed);
    Q_PROPERTY(quint8 Data_68 READ getData_68 WRITE setData_68 NOTIFY Data_68Changed);
    Q_PROPERTY(quint8 Data_69 READ getData_69 WRITE setData_69 NOTIFY Data_69Changed);
    Q_PROPERTY(quint8 Data_70 READ getData_70 WRITE setData_70 NOTIFY Data_70Changed);
    Q_PROPERTY(quint8 Data_71 READ getData_71 WRITE setData_71 NOTIFY Data_71Changed);
    Q_PROPERTY(quint8 Data_72 READ getData_72 WRITE setData_72 NOTIFY Data_72Changed);
    Q_PROPERTY(quint8 Data_73 READ getData_73 WRITE setData_73 NOTIFY Data_73Changed);
    Q_PROPERTY(quint8 Data_74 READ getData_74 WRITE setData_74 NOTIFY Data_74Changed);
    Q_PROPERTY(quint8 Data_75 READ getData_75 WRITE setData_75 NOTIFY Data_75Changed);
    Q_PROPERTY(quint8 Data_76 READ getData_76 WRITE setData_76 NOTIFY Data_76Changed);
    Q_PROPERTY(quint8 Data_77 READ getData_77 WRITE setData_77 NOTIFY Data_77Changed);
    Q_PROPERTY(quint8 Data_78 READ getData_78 WRITE setData_78 NOTIFY Data_78Changed);
    Q_PROPERTY(quint8 Data_79 READ getData_79 WRITE setData_79 NOTIFY Data_79Changed);
    Q_PROPERTY(quint8 Data_80 READ getData_80 WRITE setData_80 NOTIFY Data_80Changed);
    Q_PROPERTY(quint8 Data_81 READ getData_81 WRITE setData_81 NOTIFY Data_81Changed);
    Q_PROPERTY(quint8 Data_82 READ getData_82 WRITE setData_82 NOTIFY Data_82Changed);
    Q_PROPERTY(quint8 Data_83 READ getData_83 WRITE setData_83 NOTIFY Data_83Changed);
    Q_PROPERTY(quint8 Data_84 READ getData_84 WRITE setData_84 NOTIFY Data_84Changed);
    Q_PROPERTY(quint8 Data_85 READ getData_85 WRITE setData_85 NOTIFY Data_85Changed);
    Q_PROPERTY(quint8 Data_86 READ getData_86 WRITE setData_86 NOTIFY Data_86Changed);
    Q_PROPERTY(quint8 Data_87 READ getData_87 WRITE setData_87 NOTIFY Data_87Changed);
    Q_PROPERTY(quint8 Data_88 READ getData_88 WRITE setData_88 NOTIFY Data_88Changed);
    Q_PROPERTY(quint8 Data_89 READ getData_89 WRITE setData_89 NOTIFY Data_89Changed);
    Q_PROPERTY(quint8 Data_90 READ getData_90 WRITE setData_90 NOTIFY Data_90Changed);
    Q_PROPERTY(quint8 Data_91 READ getData_91 WRITE setData_91 NOTIFY Data_91Changed);
    Q_PROPERTY(quint8 Data_92 READ getData_92 WRITE setData_92 NOTIFY Data_92Changed);
    Q_PROPERTY(quint8 Data_93 READ getData_93 WRITE setData_93 NOTIFY Data_93Changed);
    Q_PROPERTY(quint8 Data_94 READ getData_94 WRITE setData_94 NOTIFY Data_94Changed);
    Q_PROPERTY(quint8 Data_95 READ getData_95 WRITE setData_95 NOTIFY Data_95Changed);
    Q_PROPERTY(quint8 Data_96 READ getData_96 WRITE setData_96 NOTIFY Data_96Changed);
    Q_PROPERTY(quint8 Data_97 READ getData_97 WRITE setData_97 NOTIFY Data_97Changed);
    Q_PROPERTY(quint8 Data_98 READ getData_98 WRITE setData_98 NOTIFY Data_98Changed);
    Q_PROPERTY(quint8 Data_99 READ getData_99 WRITE setData_99 NOTIFY Data_99Changed);
    Q_PROPERTY(quint8 Data_100 READ getData_100 WRITE setData_100 NOTIFY Data_100Changed);
    Q_PROPERTY(quint8 Data_101 READ getData_101 WRITE setData_101 NOTIFY Data_101Changed);
    Q_PROPERTY(quint8 Data_102 READ getData_102 WRITE setData_102 NOTIFY Data_102Changed);
    Q_PROPERTY(quint8 Data_103 READ getData_103 WRITE setData_103 NOTIFY Data_103Changed);
    Q_PROPERTY(quint8 Data_104 READ getData_104 WRITE setData_104 NOTIFY Data_104Changed);
    Q_PROPERTY(quint8 Data_105 READ getData_105 WRITE setData_105 NOTIFY Data_105Changed);
    Q_PROPERTY(quint8 Data_106 READ getData_106 WRITE setData_106 NOTIFY Data_106Changed);
    Q_PROPERTY(quint8 Data_107 READ getData_107 WRITE setData_107 NOTIFY Data_107Changed);
    Q_PROPERTY(quint8 Data_108 READ getData_108 WRITE setData_108 NOTIFY Data_108Changed);
    Q_PROPERTY(quint8 Data_109 READ getData_109 WRITE setData_109 NOTIFY Data_109Changed);
    Q_PROPERTY(quint8 Data_110 READ getData_110 WRITE setData_110 NOTIFY Data_110Changed);
    Q_PROPERTY(quint8 Data_111 READ getData_111 WRITE setData_111 NOTIFY Data_111Changed);
    Q_PROPERTY(quint8 Data_112 READ getData_112 WRITE setData_112 NOTIFY Data_112Changed);
    Q_PROPERTY(quint8 Data_113 READ getData_113 WRITE setData_113 NOTIFY Data_113Changed);
    Q_PROPERTY(quint8 Data_114 READ getData_114 WRITE setData_114 NOTIFY Data_114Changed);
    Q_PROPERTY(quint8 Data_115 READ getData_115 WRITE setData_115 NOTIFY Data_115Changed);
    Q_PROPERTY(quint8 Data_116 READ getData_116 WRITE setData_116 NOTIFY Data_116Changed);
    Q_PROPERTY(quint8 Data_117 READ getData_117 WRITE setData_117 NOTIFY Data_117Changed);
    Q_PROPERTY(quint8 Data_118 READ getData_118 WRITE setData_118 NOTIFY Data_118Changed);
    Q_PROPERTY(quint8 Data_119 READ getData_119 WRITE setData_119 NOTIFY Data_119Changed);
    Q_PROPERTY(quint8 Data_120 READ getData_120 WRITE setData_120 NOTIFY Data_120Changed);
    Q_PROPERTY(quint8 Data_121 READ getData_121 WRITE setData_121 NOTIFY Data_121Changed);
    Q_PROPERTY(quint8 Data_122 READ getData_122 WRITE setData_122 NOTIFY Data_122Changed);
    Q_PROPERTY(quint8 Data_123 READ getData_123 WRITE setData_123 NOTIFY Data_123Changed);
    Q_PROPERTY(quint8 Data_124 READ getData_124 WRITE setData_124 NOTIFY Data_124Changed);
    Q_PROPERTY(quint8 Data_125 READ getData_125 WRITE setData_125 NOTIFY Data_125Changed);
    Q_PROPERTY(quint8 Data_126 READ getData_126 WRITE setData_126 NOTIFY Data_126Changed);
    Q_PROPERTY(quint8 Data_127 READ getData_127 WRITE setData_127 NOTIFY Data_127Changed);
    Q_PROPERTY(quint8 Data_128 READ getData_128 WRITE setData_128 NOTIFY Data_128Changed);
    Q_PROPERTY(quint8 Data_129 READ getData_129 WRITE setData_129 NOTIFY Data_129Changed);
    Q_PROPERTY(quint8 Data_130 READ getData_130 WRITE setData_130 NOTIFY Data_130Changed);
    Q_PROPERTY(quint8 Data_131 READ getData_131 WRITE setData_131 NOTIFY Data_131Changed);
    Q_PROPERTY(quint8 Data_132 READ getData_132 WRITE setData_132 NOTIFY Data_132Changed);
    Q_PROPERTY(quint8 Data_133 READ getData_133 WRITE setData_133 NOTIFY Data_133Changed);
    Q_PROPERTY(quint8 Data_134 READ getData_134 WRITE setData_134 NOTIFY Data_134Changed);
    Q_PROPERTY(quint8 Data_135 READ getData_135 WRITE setData_135 NOTIFY Data_135Changed);
    Q_PROPERTY(quint8 Data_136 READ getData_136 WRITE setData_136 NOTIFY Data_136Changed);
    Q_PROPERTY(quint8 Data_137 READ getData_137 WRITE setData_137 NOTIFY Data_137Changed);
    Q_PROPERTY(quint8 Data_138 READ getData_138 WRITE setData_138 NOTIFY Data_138Changed);
    Q_PROPERTY(quint8 Data_139 READ getData_139 WRITE setData_139 NOTIFY Data_139Changed);
    Q_PROPERTY(quint8 Data_140 READ getData_140 WRITE setData_140 NOTIFY Data_140Changed);
    Q_PROPERTY(quint8 Data_141 READ getData_141 WRITE setData_141 NOTIFY Data_141Changed);
    Q_PROPERTY(quint8 Data_142 READ getData_142 WRITE setData_142 NOTIFY Data_142Changed);
    Q_PROPERTY(quint8 Data_143 READ getData_143 WRITE setData_143 NOTIFY Data_143Changed);
    Q_PROPERTY(quint8 Data_144 READ getData_144 WRITE setData_144 NOTIFY Data_144Changed);
    Q_PROPERTY(quint8 Data_145 READ getData_145 WRITE setData_145 NOTIFY Data_145Changed);
    Q_PROPERTY(quint8 Data_146 READ getData_146 WRITE setData_146 NOTIFY Data_146Changed);
    Q_PROPERTY(quint8 Data_147 READ getData_147 WRITE setData_147 NOTIFY Data_147Changed);
    Q_PROPERTY(quint8 Data_148 READ getData_148 WRITE setData_148 NOTIFY Data_148Changed);
    Q_PROPERTY(quint8 Data_149 READ getData_149 WRITE setData_149 NOTIFY Data_149Changed);
    Q_PROPERTY(quint8 Data_150 READ getData_150 WRITE setData_150 NOTIFY Data_150Changed);
    Q_PROPERTY(quint8 Data_151 READ getData_151 WRITE setData_151 NOTIFY Data_151Changed);
    Q_PROPERTY(quint8 Data_152 READ getData_152 WRITE setData_152 NOTIFY Data_152Changed);
    Q_PROPERTY(quint8 Data_153 READ getData_153 WRITE setData_153 NOTIFY Data_153Changed);
    Q_PROPERTY(quint8 Data_154 READ getData_154 WRITE setData_154 NOTIFY Data_154Changed);
    Q_PROPERTY(quint8 Data_155 READ getData_155 WRITE setData_155 NOTIFY Data_155Changed);
    Q_PROPERTY(quint8 Data_156 READ getData_156 WRITE setData_156 NOTIFY Data_156Changed);
    Q_PROPERTY(quint8 Data_157 READ getData_157 WRITE setData_157 NOTIFY Data_157Changed);
    Q_PROPERTY(quint8 Data_158 READ getData_158 WRITE setData_158 NOTIFY Data_158Changed);
    Q_PROPERTY(quint8 Data_159 READ getData_159 WRITE setData_159 NOTIFY Data_159Changed);
    Q_PROPERTY(quint8 Data_160 READ getData_160 WRITE setData_160 NOTIFY Data_160Changed);
    Q_PROPERTY(quint8 Data_161 READ getData_161 WRITE setData_161 NOTIFY Data_161Changed);
    Q_PROPERTY(quint8 Data_162 READ getData_162 WRITE setData_162 NOTIFY Data_162Changed);
    Q_PROPERTY(quint8 Data_163 READ getData_163 WRITE setData_163 NOTIFY Data_163Changed);
    Q_PROPERTY(quint8 Data_164 READ getData_164 WRITE setData_164 NOTIFY Data_164Changed);
    Q_PROPERTY(quint8 Data_165 READ getData_165 WRITE setData_165 NOTIFY Data_165Changed);
    Q_PROPERTY(quint8 Data_166 READ getData_166 WRITE setData_166 NOTIFY Data_166Changed);
    Q_PROPERTY(quint8 Data_167 READ getData_167 WRITE setData_167 NOTIFY Data_167Changed);
    Q_PROPERTY(quint8 Data_168 READ getData_168 WRITE setData_168 NOTIFY Data_168Changed);
    Q_PROPERTY(quint8 Data_169 READ getData_169 WRITE setData_169 NOTIFY Data_169Changed);
    Q_PROPERTY(quint8 Data_170 READ getData_170 WRITE setData_170 NOTIFY Data_170Changed);
    Q_PROPERTY(quint8 Data_171 READ getData_171 WRITE setData_171 NOTIFY Data_171Changed);
    Q_PROPERTY(quint8 Data_172 READ getData_172 WRITE setData_172 NOTIFY Data_172Changed);
    Q_PROPERTY(quint8 Data_173 READ getData_173 WRITE setData_173 NOTIFY Data_173Changed);
    Q_PROPERTY(quint8 Data_174 READ getData_174 WRITE setData_174 NOTIFY Data_174Changed);
    Q_PROPERTY(quint8 Data_175 READ getData_175 WRITE setData_175 NOTIFY Data_175Changed);
    Q_PROPERTY(quint8 Data_176 READ getData_176 WRITE setData_176 NOTIFY Data_176Changed);
    Q_PROPERTY(quint8 Data_177 READ getData_177 WRITE setData_177 NOTIFY Data_177Changed);
    Q_PROPERTY(quint8 Data_178 READ getData_178 WRITE setData_178 NOTIFY Data_178Changed);
    Q_PROPERTY(quint8 Data_179 READ getData_179 WRITE setData_179 NOTIFY Data_179Changed);
    Q_PROPERTY(quint8 Data_180 READ getData_180 WRITE setData_180 NOTIFY Data_180Changed);
    Q_PROPERTY(quint8 Data_181 READ getData_181 WRITE setData_181 NOTIFY Data_181Changed);
    Q_PROPERTY(quint8 Data_182 READ getData_182 WRITE setData_182 NOTIFY Data_182Changed);
    Q_PROPERTY(quint8 Data_183 READ getData_183 WRITE setData_183 NOTIFY Data_183Changed);
    Q_PROPERTY(quint8 Data_184 READ getData_184 WRITE setData_184 NOTIFY Data_184Changed);
    Q_PROPERTY(quint8 Data_185 READ getData_185 WRITE setData_185 NOTIFY Data_185Changed);
    Q_PROPERTY(quint8 Data_186 READ getData_186 WRITE setData_186 NOTIFY Data_186Changed);
    Q_PROPERTY(quint8 Data_187 READ getData_187 WRITE setData_187 NOTIFY Data_187Changed);
    Q_PROPERTY(quint8 Data_188 READ getData_188 WRITE setData_188 NOTIFY Data_188Changed);
    Q_PROPERTY(quint8 Data_189 READ getData_189 WRITE setData_189 NOTIFY Data_189Changed);
    Q_PROPERTY(quint8 Data_190 READ getData_190 WRITE setData_190 NOTIFY Data_190Changed);
    Q_PROPERTY(quint8 Data_191 READ getData_191 WRITE setData_191 NOTIFY Data_191Changed);
    Q_PROPERTY(quint8 Data_192 READ getData_192 WRITE setData_192 NOTIFY Data_192Changed);
    Q_PROPERTY(quint8 Data_193 READ getData_193 WRITE setData_193 NOTIFY Data_193Changed);
    Q_PROPERTY(quint8 Data_194 READ getData_194 WRITE setData_194 NOTIFY Data_194Changed);
    Q_PROPERTY(quint8 Data_195 READ getData_195 WRITE setData_195 NOTIFY Data_195Changed);
    Q_PROPERTY(quint8 Data_196 READ getData_196 WRITE setData_196 NOTIFY Data_196Changed);
    Q_PROPERTY(quint8 Data_197 READ getData_197 WRITE setData_197 NOTIFY Data_197Changed);
    Q_PROPERTY(quint8 Data_198 READ getData_198 WRITE setData_198 NOTIFY Data_198Changed);
    Q_PROPERTY(quint8 Data_199 READ getData_199 WRITE setData_199 NOTIFY Data_199Changed);


public:
    // Field structure
    typedef struct {
        quint32 FlightTime;
        quint32 ObjectID;
        quint16 Flight;
        quint16 Entry;
        quint16 InstanceID;
        quint16 Size;
        quint8 Type;
        quint8 Data[200];

    } __attribute__((packed)) DataFields;

    // Field information
    // Field FlightTime information
    // Field ObjectID information
    // Field Flight information
    // Field Entry information
    // Field InstanceID information
    // Field Size information
    // Field Type information
    /* Enumeration options for field Type */
    typedef enum { TYPE_EMPTY=0, TYPE_TEXT=1, TYPE_UAVOBJECT=2, TYPE_MULTIPLEUAVOBJECTS=3 } TypeOptions;
    // Field Data information
    /* Number of elements for field Data */
    static const quint32 DATA_NUMELEM = 200;

  
    // Constants
    static const quint32 OBJID = 0x233CDCC0;
    static const QString NAME;
    static const QString DESCRIPTION;
    static const QString CATEGORY;
    static const bool ISSINGLEINST = 1;
    static const bool ISSETTINGS = 0;
    static const quint32 NUMBYTES = sizeof(DataFields);

    // Functions
    DebugLogEntry();

    DataFields getData();
    void setData(const DataFields& data);
    Metadata getDefaultMetadata();
    UAVDataObject* clone(quint32 instID);
	UAVDataObject* dirtyClone();
	
    static DebugLogEntry* GetInstance(UAVObjectManager* objMngr, quint32 instID = 0);

    Q_INVOKABLE quint32 getFlightTime() const;
    Q_INVOKABLE quint32 getObjectID() const;
    Q_INVOKABLE quint16 getFlight() const;
    Q_INVOKABLE quint16 getEntry() const;
    Q_INVOKABLE quint16 getInstanceID() const;
    Q_INVOKABLE quint16 getSize() const;
    Q_INVOKABLE quint8 getType() const;
    Q_INVOKABLE quint8 getData(quint32 index) const;
    Q_INVOKABLE quint8 getData_0() const;
    Q_INVOKABLE quint8 getData_1() const;
    Q_INVOKABLE quint8 getData_2() const;
    Q_INVOKABLE quint8 getData_3() const;
    Q_INVOKABLE quint8 getData_4() const;
    Q_INVOKABLE quint8 getData_5() const;
    Q_INVOKABLE quint8 getData_6() const;
    Q_INVOKABLE quint8 getData_7() const;
    Q_INVOKABLE quint8 getData_8() const;
    Q_INVOKABLE quint8 getData_9() const;
    Q_INVOKABLE quint8 getData_10() const;
    Q_INVOKABLE quint8 getData_11() const;
    Q_INVOKABLE quint8 getData_12() const;
    Q_INVOKABLE quint8 getData_13() const;
    Q_INVOKABLE quint8 getData_14() const;
    Q_INVOKABLE quint8 getData_15() const;
    Q_INVOKABLE quint8 getData_16() const;
    Q_INVOKABLE quint8 getData_17() const;
    Q_INVOKABLE quint8 getData_18() const;
    Q_INVOKABLE quint8 getData_19() const;
    Q_INVOKABLE quint8 getData_20() const;
    Q_INVOKABLE quint8 getData_21() const;
    Q_INVOKABLE quint8 getData_22() const;
    Q_INVOKABLE quint8 getData_23() const;
    Q_INVOKABLE quint8 getData_24() const;
    Q_INVOKABLE quint8 getData_25() const;
    Q_INVOKABLE quint8 getData_26() const;
    Q_INVOKABLE quint8 getData_27() const;
    Q_INVOKABLE quint8 getData_28() const;
    Q_INVOKABLE quint8 getData_29() const;
    Q_INVOKABLE quint8 getData_30() const;
    Q_INVOKABLE quint8 getData_31() const;
    Q_INVOKABLE quint8 getData_32() const;
    Q_INVOKABLE quint8 getData_33() const;
    Q_INVOKABLE quint8 getData_34() const;
    Q_INVOKABLE quint8 getData_35() const;
    Q_INVOKABLE quint8 getData_36() const;
    Q_INVOKABLE quint8 getData_37() const;
    Q_INVOKABLE quint8 getData_38() const;
    Q_INVOKABLE quint8 getData_39() const;
    Q_INVOKABLE quint8 getData_40() const;
    Q_INVOKABLE quint8 getData_41() const;
    Q_INVOKABLE quint8 getData_42() const;
    Q_INVOKABLE quint8 getData_43() const;
    Q_INVOKABLE quint8 getData_44() const;
    Q_INVOKABLE quint8 getData_45() const;
    Q_INVOKABLE quint8 getData_46() const;
    Q_INVOKABLE quint8 getData_47() const;
    Q_INVOKABLE quint8 getData_48() const;
    Q_INVOKABLE quint8 getData_49() const;
    Q_INVOKABLE quint8 getData_50() const;
    Q_INVOKABLE quint8 getData_51() const;
    Q_INVOKABLE quint8 getData_52() const;
    Q_INVOKABLE quint8 getData_53() const;
    Q_INVOKABLE quint8 getData_54() const;
    Q_INVOKABLE quint8 getData_55() const;
    Q_INVOKABLE quint8 getData_56() const;
    Q_INVOKABLE quint8 getData_57() const;
    Q_INVOKABLE quint8 getData_58() const;
    Q_INVOKABLE quint8 getData_59() const;
    Q_INVOKABLE quint8 getData_60() const;
    Q_INVOKABLE quint8 getData_61() const;
    Q_INVOKABLE quint8 getData_62() const;
    Q_INVOKABLE quint8 getData_63() const;
    Q_INVOKABLE quint8 getData_64() const;
    Q_INVOKABLE quint8 getData_65() const;
    Q_INVOKABLE quint8 getData_66() const;
    Q_INVOKABLE quint8 getData_67() const;
    Q_INVOKABLE quint8 getData_68() const;
    Q_INVOKABLE quint8 getData_69() const;
    Q_INVOKABLE quint8 getData_70() const;
    Q_INVOKABLE quint8 getData_71() const;
    Q_INVOKABLE quint8 getData_72() const;
    Q_INVOKABLE quint8 getData_73() const;
    Q_INVOKABLE quint8 getData_74() const;
    Q_INVOKABLE quint8 getData_75() const;
    Q_INVOKABLE quint8 getData_76() const;
    Q_INVOKABLE quint8 getData_77() const;
    Q_INVOKABLE quint8 getData_78() const;
    Q_INVOKABLE quint8 getData_79() const;
    Q_INVOKABLE quint8 getData_80() const;
    Q_INVOKABLE quint8 getData_81() const;
    Q_INVOKABLE quint8 getData_82() const;
    Q_INVOKABLE quint8 getData_83() const;
    Q_INVOKABLE quint8 getData_84() const;
    Q_INVOKABLE quint8 getData_85() const;
    Q_INVOKABLE quint8 getData_86() const;
    Q_INVOKABLE quint8 getData_87() const;
    Q_INVOKABLE quint8 getData_88() const;
    Q_INVOKABLE quint8 getData_89() const;
    Q_INVOKABLE quint8 getData_90() const;
    Q_INVOKABLE quint8 getData_91() const;
    Q_INVOKABLE quint8 getData_92() const;
    Q_INVOKABLE quint8 getData_93() const;
    Q_INVOKABLE quint8 getData_94() const;
    Q_INVOKABLE quint8 getData_95() const;
    Q_INVOKABLE quint8 getData_96() const;
    Q_INVOKABLE quint8 getData_97() const;
    Q_INVOKABLE quint8 getData_98() const;
    Q_INVOKABLE quint8 getData_99() const;
    Q_INVOKABLE quint8 getData_100() const;
    Q_INVOKABLE quint8 getData_101() const;
    Q_INVOKABLE quint8 getData_102() const;
    Q_INVOKABLE quint8 getData_103() const;
    Q_INVOKABLE quint8 getData_104() const;
    Q_INVOKABLE quint8 getData_105() const;
    Q_INVOKABLE quint8 getData_106() const;
    Q_INVOKABLE quint8 getData_107() const;
    Q_INVOKABLE quint8 getData_108() const;
    Q_INVOKABLE quint8 getData_109() const;
    Q_INVOKABLE quint8 getData_110() const;
    Q_INVOKABLE quint8 getData_111() const;
    Q_INVOKABLE quint8 getData_112() const;
    Q_INVOKABLE quint8 getData_113() const;
    Q_INVOKABLE quint8 getData_114() const;
    Q_INVOKABLE quint8 getData_115() const;
    Q_INVOKABLE quint8 getData_116() const;
    Q_INVOKABLE quint8 getData_117() const;
    Q_INVOKABLE quint8 getData_118() const;
    Q_INVOKABLE quint8 getData_119() const;
    Q_INVOKABLE quint8 getData_120() const;
    Q_INVOKABLE quint8 getData_121() const;
    Q_INVOKABLE quint8 getData_122() const;
    Q_INVOKABLE quint8 getData_123() const;
    Q_INVOKABLE quint8 getData_124() const;
    Q_INVOKABLE quint8 getData_125() const;
    Q_INVOKABLE quint8 getData_126() const;
    Q_INVOKABLE quint8 getData_127() const;
    Q_INVOKABLE quint8 getData_128() const;
    Q_INVOKABLE quint8 getData_129() const;
    Q_INVOKABLE quint8 getData_130() const;
    Q_INVOKABLE quint8 getData_131() const;
    Q_INVOKABLE quint8 getData_132() const;
    Q_INVOKABLE quint8 getData_133() const;
    Q_INVOKABLE quint8 getData_134() const;
    Q_INVOKABLE quint8 getData_135() const;
    Q_INVOKABLE quint8 getData_136() const;
    Q_INVOKABLE quint8 getData_137() const;
    Q_INVOKABLE quint8 getData_138() const;
    Q_INVOKABLE quint8 getData_139() const;
    Q_INVOKABLE quint8 getData_140() const;
    Q_INVOKABLE quint8 getData_141() const;
    Q_INVOKABLE quint8 getData_142() const;
    Q_INVOKABLE quint8 getData_143() const;
    Q_INVOKABLE quint8 getData_144() const;
    Q_INVOKABLE quint8 getData_145() const;
    Q_INVOKABLE quint8 getData_146() const;
    Q_INVOKABLE quint8 getData_147() const;
    Q_INVOKABLE quint8 getData_148() const;
    Q_INVOKABLE quint8 getData_149() const;
    Q_INVOKABLE quint8 getData_150() const;
    Q_INVOKABLE quint8 getData_151() const;
    Q_INVOKABLE quint8 getData_152() const;
    Q_INVOKABLE quint8 getData_153() const;
    Q_INVOKABLE quint8 getData_154() const;
    Q_INVOKABLE quint8 getData_155() const;
    Q_INVOKABLE quint8 getData_156() const;
    Q_INVOKABLE quint8 getData_157() const;
    Q_INVOKABLE quint8 getData_158() const;
    Q_INVOKABLE quint8 getData_159() const;
    Q_INVOKABLE quint8 getData_160() const;
    Q_INVOKABLE quint8 getData_161() const;
    Q_INVOKABLE quint8 getData_162() const;
    Q_INVOKABLE quint8 getData_163() const;
    Q_INVOKABLE quint8 getData_164() const;
    Q_INVOKABLE quint8 getData_165() const;
    Q_INVOKABLE quint8 getData_166() const;
    Q_INVOKABLE quint8 getData_167() const;
    Q_INVOKABLE quint8 getData_168() const;
    Q_INVOKABLE quint8 getData_169() const;
    Q_INVOKABLE quint8 getData_170() const;
    Q_INVOKABLE quint8 getData_171() const;
    Q_INVOKABLE quint8 getData_172() const;
    Q_INVOKABLE quint8 getData_173() const;
    Q_INVOKABLE quint8 getData_174() const;
    Q_INVOKABLE quint8 getData_175() const;
    Q_INVOKABLE quint8 getData_176() const;
    Q_INVOKABLE quint8 getData_177() const;
    Q_INVOKABLE quint8 getData_178() const;
    Q_INVOKABLE quint8 getData_179() const;
    Q_INVOKABLE quint8 getData_180() const;
    Q_INVOKABLE quint8 getData_181() const;
    Q_INVOKABLE quint8 getData_182() const;
    Q_INVOKABLE quint8 getData_183() const;
    Q_INVOKABLE quint8 getData_184() const;
    Q_INVOKABLE quint8 getData_185() const;
    Q_INVOKABLE quint8 getData_186() const;
    Q_INVOKABLE quint8 getData_187() const;
    Q_INVOKABLE quint8 getData_188() const;
    Q_INVOKABLE quint8 getData_189() const;
    Q_INVOKABLE quint8 getData_190() const;
    Q_INVOKABLE quint8 getData_191() const;
    Q_INVOKABLE quint8 getData_192() const;
    Q_INVOKABLE quint8 getData_193() const;
    Q_INVOKABLE quint8 getData_194() const;
    Q_INVOKABLE quint8 getData_195() const;
    Q_INVOKABLE quint8 getData_196() const;
    Q_INVOKABLE quint8 getData_197() const;
    Q_INVOKABLE quint8 getData_198() const;
    Q_INVOKABLE quint8 getData_199() const;


public slots:
    void setFlightTime(quint32 value);
    void setObjectID(quint32 value);
    void setFlight(quint16 value);
    void setEntry(quint16 value);
    void setInstanceID(quint16 value);
    void setSize(quint16 value);
    void setType(quint8 value);
    void setData(quint32 index, quint8 value);
    void setData_0(quint8 value);
    void setData_1(quint8 value);
    void setData_2(quint8 value);
    void setData_3(quint8 value);
    void setData_4(quint8 value);
    void setData_5(quint8 value);
    void setData_6(quint8 value);
    void setData_7(quint8 value);
    void setData_8(quint8 value);
    void setData_9(quint8 value);
    void setData_10(quint8 value);
    void setData_11(quint8 value);
    void setData_12(quint8 value);
    void setData_13(quint8 value);
    void setData_14(quint8 value);
    void setData_15(quint8 value);
    void setData_16(quint8 value);
    void setData_17(quint8 value);
    void setData_18(quint8 value);
    void setData_19(quint8 value);
    void setData_20(quint8 value);
    void setData_21(quint8 value);
    void setData_22(quint8 value);
    void setData_23(quint8 value);
    void setData_24(quint8 value);
    void setData_25(quint8 value);
    void setData_26(quint8 value);
    void setData_27(quint8 value);
    void setData_28(quint8 value);
    void setData_29(quint8 value);
    void setData_30(quint8 value);
    void setData_31(quint8 value);
    void setData_32(quint8 value);
    void setData_33(quint8 value);
    void setData_34(quint8 value);
    void setData_35(quint8 value);
    void setData_36(quint8 value);
    void setData_37(quint8 value);
    void setData_38(quint8 value);
    void setData_39(quint8 value);
    void setData_40(quint8 value);
    void setData_41(quint8 value);
    void setData_42(quint8 value);
    void setData_43(quint8 value);
    void setData_44(quint8 value);
    void setData_45(quint8 value);
    void setData_46(quint8 value);
    void setData_47(quint8 value);
    void setData_48(quint8 value);
    void setData_49(quint8 value);
    void setData_50(quint8 value);
    void setData_51(quint8 value);
    void setData_52(quint8 value);
    void setData_53(quint8 value);
    void setData_54(quint8 value);
    void setData_55(quint8 value);
    void setData_56(quint8 value);
    void setData_57(quint8 value);
    void setData_58(quint8 value);
    void setData_59(quint8 value);
    void setData_60(quint8 value);
    void setData_61(quint8 value);
    void setData_62(quint8 value);
    void setData_63(quint8 value);
    void setData_64(quint8 value);
    void setData_65(quint8 value);
    void setData_66(quint8 value);
    void setData_67(quint8 value);
    void setData_68(quint8 value);
    void setData_69(quint8 value);
    void setData_70(quint8 value);
    void setData_71(quint8 value);
    void setData_72(quint8 value);
    void setData_73(quint8 value);
    void setData_74(quint8 value);
    void setData_75(quint8 value);
    void setData_76(quint8 value);
    void setData_77(quint8 value);
    void setData_78(quint8 value);
    void setData_79(quint8 value);
    void setData_80(quint8 value);
    void setData_81(quint8 value);
    void setData_82(quint8 value);
    void setData_83(quint8 value);
    void setData_84(quint8 value);
    void setData_85(quint8 value);
    void setData_86(quint8 value);
    void setData_87(quint8 value);
    void setData_88(quint8 value);
    void setData_89(quint8 value);
    void setData_90(quint8 value);
    void setData_91(quint8 value);
    void setData_92(quint8 value);
    void setData_93(quint8 value);
    void setData_94(quint8 value);
    void setData_95(quint8 value);
    void setData_96(quint8 value);
    void setData_97(quint8 value);
    void setData_98(quint8 value);
    void setData_99(quint8 value);
    void setData_100(quint8 value);
    void setData_101(quint8 value);
    void setData_102(quint8 value);
    void setData_103(quint8 value);
    void setData_104(quint8 value);
    void setData_105(quint8 value);
    void setData_106(quint8 value);
    void setData_107(quint8 value);
    void setData_108(quint8 value);
    void setData_109(quint8 value);
    void setData_110(quint8 value);
    void setData_111(quint8 value);
    void setData_112(quint8 value);
    void setData_113(quint8 value);
    void setData_114(quint8 value);
    void setData_115(quint8 value);
    void setData_116(quint8 value);
    void setData_117(quint8 value);
    void setData_118(quint8 value);
    void setData_119(quint8 value);
    void setData_120(quint8 value);
    void setData_121(quint8 value);
    void setData_122(quint8 value);
    void setData_123(quint8 value);
    void setData_124(quint8 value);
    void setData_125(quint8 value);
    void setData_126(quint8 value);
    void setData_127(quint8 value);
    void setData_128(quint8 value);
    void setData_129(quint8 value);
    void setData_130(quint8 value);
    void setData_131(quint8 value);
    void setData_132(quint8 value);
    void setData_133(quint8 value);
    void setData_134(quint8 value);
    void setData_135(quint8 value);
    void setData_136(quint8 value);
    void setData_137(quint8 value);
    void setData_138(quint8 value);
    void setData_139(quint8 value);
    void setData_140(quint8 value);
    void setData_141(quint8 value);
    void setData_142(quint8 value);
    void setData_143(quint8 value);
    void setData_144(quint8 value);
    void setData_145(quint8 value);
    void setData_146(quint8 value);
    void setData_147(quint8 value);
    void setData_148(quint8 value);
    void setData_149(quint8 value);
    void setData_150(quint8 value);
    void setData_151(quint8 value);
    void setData_152(quint8 value);
    void setData_153(quint8 value);
    void setData_154(quint8 value);
    void setData_155(quint8 value);
    void setData_156(quint8 value);
    void setData_157(quint8 value);
    void setData_158(quint8 value);
    void setData_159(quint8 value);
    void setData_160(quint8 value);
    void setData_161(quint8 value);
    void setData_162(quint8 value);
    void setData_163(quint8 value);
    void setData_164(quint8 value);
    void setData_165(quint8 value);
    void setData_166(quint8 value);
    void setData_167(quint8 value);
    void setData_168(quint8 value);
    void setData_169(quint8 value);
    void setData_170(quint8 value);
    void setData_171(quint8 value);
    void setData_172(quint8 value);
    void setData_173(quint8 value);
    void setData_174(quint8 value);
    void setData_175(quint8 value);
    void setData_176(quint8 value);
    void setData_177(quint8 value);
    void setData_178(quint8 value);
    void setData_179(quint8 value);
    void setData_180(quint8 value);
    void setData_181(quint8 value);
    void setData_182(quint8 value);
    void setData_183(quint8 value);
    void setData_184(quint8 value);
    void setData_185(quint8 value);
    void setData_186(quint8 value);
    void setData_187(quint8 value);
    void setData_188(quint8 value);
    void setData_189(quint8 value);
    void setData_190(quint8 value);
    void setData_191(quint8 value);
    void setData_192(quint8 value);
    void setData_193(quint8 value);
    void setData_194(quint8 value);
    void setData_195(quint8 value);
    void setData_196(quint8 value);
    void setData_197(quint8 value);
    void setData_198(quint8 value);
    void setData_199(quint8 value);


signals:
    void FlightTimeChanged(quint32 value);
    void ObjectIDChanged(quint32 value);
    void FlightChanged(quint16 value);
    void EntryChanged(quint16 value);
    void InstanceIDChanged(quint16 value);
    void SizeChanged(quint16 value);
    void TypeChanged(quint8 value);
    void DataChanged(quint32 index, quint8 value);
    void Data_0Changed(quint8 value);
    void Data_1Changed(quint8 value);
    void Data_2Changed(quint8 value);
    void Data_3Changed(quint8 value);
    void Data_4Changed(quint8 value);
    void Data_5Changed(quint8 value);
    void Data_6Changed(quint8 value);
    void Data_7Changed(quint8 value);
    void Data_8Changed(quint8 value);
    void Data_9Changed(quint8 value);
    void Data_10Changed(quint8 value);
    void Data_11Changed(quint8 value);
    void Data_12Changed(quint8 value);
    void Data_13Changed(quint8 value);
    void Data_14Changed(quint8 value);
    void Data_15Changed(quint8 value);
    void Data_16Changed(quint8 value);
    void Data_17Changed(quint8 value);
    void Data_18Changed(quint8 value);
    void Data_19Changed(quint8 value);
    void Data_20Changed(quint8 value);
    void Data_21Changed(quint8 value);
    void Data_22Changed(quint8 value);
    void Data_23Changed(quint8 value);
    void Data_24Changed(quint8 value);
    void Data_25Changed(quint8 value);
    void Data_26Changed(quint8 value);
    void Data_27Changed(quint8 value);
    void Data_28Changed(quint8 value);
    void Data_29Changed(quint8 value);
    void Data_30Changed(quint8 value);
    void Data_31Changed(quint8 value);
    void Data_32Changed(quint8 value);
    void Data_33Changed(quint8 value);
    void Data_34Changed(quint8 value);
    void Data_35Changed(quint8 value);
    void Data_36Changed(quint8 value);
    void Data_37Changed(quint8 value);
    void Data_38Changed(quint8 value);
    void Data_39Changed(quint8 value);
    void Data_40Changed(quint8 value);
    void Data_41Changed(quint8 value);
    void Data_42Changed(quint8 value);
    void Data_43Changed(quint8 value);
    void Data_44Changed(quint8 value);
    void Data_45Changed(quint8 value);
    void Data_46Changed(quint8 value);
    void Data_47Changed(quint8 value);
    void Data_48Changed(quint8 value);
    void Data_49Changed(quint8 value);
    void Data_50Changed(quint8 value);
    void Data_51Changed(quint8 value);
    void Data_52Changed(quint8 value);
    void Data_53Changed(quint8 value);
    void Data_54Changed(quint8 value);
    void Data_55Changed(quint8 value);
    void Data_56Changed(quint8 value);
    void Data_57Changed(quint8 value);
    void Data_58Changed(quint8 value);
    void Data_59Changed(quint8 value);
    void Data_60Changed(quint8 value);
    void Data_61Changed(quint8 value);
    void Data_62Changed(quint8 value);
    void Data_63Changed(quint8 value);
    void Data_64Changed(quint8 value);
    void Data_65Changed(quint8 value);
    void Data_66Changed(quint8 value);
    void Data_67Changed(quint8 value);
    void Data_68Changed(quint8 value);
    void Data_69Changed(quint8 value);
    void Data_70Changed(quint8 value);
    void Data_71Changed(quint8 value);
    void Data_72Changed(quint8 value);
    void Data_73Changed(quint8 value);
    void Data_74Changed(quint8 value);
    void Data_75Changed(quint8 value);
    void Data_76Changed(quint8 value);
    void Data_77Changed(quint8 value);
    void Data_78Changed(quint8 value);
    void Data_79Changed(quint8 value);
    void Data_80Changed(quint8 value);
    void Data_81Changed(quint8 value);
    void Data_82Changed(quint8 value);
    void Data_83Changed(quint8 value);
    void Data_84Changed(quint8 value);
    void Data_85Changed(quint8 value);
    void Data_86Changed(quint8 value);
    void Data_87Changed(quint8 value);
    void Data_88Changed(quint8 value);
    void Data_89Changed(quint8 value);
    void Data_90Changed(quint8 value);
    void Data_91Changed(quint8 value);
    void Data_92Changed(quint8 value);
    void Data_93Changed(quint8 value);
    void Data_94Changed(quint8 value);
    void Data_95Changed(quint8 value);
    void Data_96Changed(quint8 value);
    void Data_97Changed(quint8 value);
    void Data_98Changed(quint8 value);
    void Data_99Changed(quint8 value);
    void Data_100Changed(quint8 value);
    void Data_101Changed(quint8 value);
    void Data_102Changed(quint8 value);
    void Data_103Changed(quint8 value);
    void Data_104Changed(quint8 value);
    void Data_105Changed(quint8 value);
    void Data_106Changed(quint8 value);
    void Data_107Changed(quint8 value);
    void Data_108Changed(quint8 value);
    void Data_109Changed(quint8 value);
    void Data_110Changed(quint8 value);
    void Data_111Changed(quint8 value);
    void Data_112Changed(quint8 value);
    void Data_113Changed(quint8 value);
    void Data_114Changed(quint8 value);
    void Data_115Changed(quint8 value);
    void Data_116Changed(quint8 value);
    void Data_117Changed(quint8 value);
    void Data_118Changed(quint8 value);
    void Data_119Changed(quint8 value);
    void Data_120Changed(quint8 value);
    void Data_121Changed(quint8 value);
    void Data_122Changed(quint8 value);
    void Data_123Changed(quint8 value);
    void Data_124Changed(quint8 value);
    void Data_125Changed(quint8 value);
    void Data_126Changed(quint8 value);
    void Data_127Changed(quint8 value);
    void Data_128Changed(quint8 value);
    void Data_129Changed(quint8 value);
    void Data_130Changed(quint8 value);
    void Data_131Changed(quint8 value);
    void Data_132Changed(quint8 value);
    void Data_133Changed(quint8 value);
    void Data_134Changed(quint8 value);
    void Data_135Changed(quint8 value);
    void Data_136Changed(quint8 value);
    void Data_137Changed(quint8 value);
    void Data_138Changed(quint8 value);
    void Data_139Changed(quint8 value);
    void Data_140Changed(quint8 value);
    void Data_141Changed(quint8 value);
    void Data_142Changed(quint8 value);
    void Data_143Changed(quint8 value);
    void Data_144Changed(quint8 value);
    void Data_145Changed(quint8 value);
    void Data_146Changed(quint8 value);
    void Data_147Changed(quint8 value);
    void Data_148Changed(quint8 value);
    void Data_149Changed(quint8 value);
    void Data_150Changed(quint8 value);
    void Data_151Changed(quint8 value);
    void Data_152Changed(quint8 value);
    void Data_153Changed(quint8 value);
    void Data_154Changed(quint8 value);
    void Data_155Changed(quint8 value);
    void Data_156Changed(quint8 value);
    void Data_157Changed(quint8 value);
    void Data_158Changed(quint8 value);
    void Data_159Changed(quint8 value);
    void Data_160Changed(quint8 value);
    void Data_161Changed(quint8 value);
    void Data_162Changed(quint8 value);
    void Data_163Changed(quint8 value);
    void Data_164Changed(quint8 value);
    void Data_165Changed(quint8 value);
    void Data_166Changed(quint8 value);
    void Data_167Changed(quint8 value);
    void Data_168Changed(quint8 value);
    void Data_169Changed(quint8 value);
    void Data_170Changed(quint8 value);
    void Data_171Changed(quint8 value);
    void Data_172Changed(quint8 value);
    void Data_173Changed(quint8 value);
    void Data_174Changed(quint8 value);
    void Data_175Changed(quint8 value);
    void Data_176Changed(quint8 value);
    void Data_177Changed(quint8 value);
    void Data_178Changed(quint8 value);
    void Data_179Changed(quint8 value);
    void Data_180Changed(quint8 value);
    void Data_181Changed(quint8 value);
    void Data_182Changed(quint8 value);
    void Data_183Changed(quint8 value);
    void Data_184Changed(quint8 value);
    void Data_185Changed(quint8 value);
    void Data_186Changed(quint8 value);
    void Data_187Changed(quint8 value);
    void Data_188Changed(quint8 value);
    void Data_189Changed(quint8 value);
    void Data_190Changed(quint8 value);
    void Data_191Changed(quint8 value);
    void Data_192Changed(quint8 value);
    void Data_193Changed(quint8 value);
    void Data_194Changed(quint8 value);
    void Data_195Changed(quint8 value);
    void Data_196Changed(quint8 value);
    void Data_197Changed(quint8 value);
    void Data_198Changed(quint8 value);
    void Data_199Changed(quint8 value);


private slots:
    void emitNotifications();
	
private:
    DataFields data;

    void setDefaultFieldValues();

};

#endif // DEBUGLOGENTRY_H
