/*
  * !!! Autogenerated from flightmodesettings.xml Do NOT Edit !!!
  *
  * Routines for OpenPilot UAVObject dissection
  * Copyright 2012 Stacey Sheldon <stac@solidgoldbomb.org>
  *
  * $Id$
  *
  * Wireshark - Network traffic analyzer
  * By Gerald Combs <gerald@wireshark.org>
  * Copyright 1998 Gerald Combs
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU General Public License
  * as published by the Free Software Foundation; either version 2
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program; if not, write to the Free Software
  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <epan/packet.h>
#include <epan/ptvcursor.h>	/* ptvcursor_* */

#include <glib.h>
#include <string.h>

static int proto_uavo = -1;

/* Subtree expansion tracking */
static gint ett_uavo = -1;
static gint ett_flightmodesettings_PositionHoldOffset = -1;
static gint ett_flightmodesettings_Stabilization1Settings = -1;
static gint ett_flightmodesettings_Stabilization2Settings = -1;
static gint ett_flightmodesettings_Stabilization3Settings = -1;
static gint ett_flightmodesettings_Stabilization4Settings = -1;
static gint ett_flightmodesettings_Stabilization5Settings = -1;
static gint ett_flightmodesettings_Stabilization6Settings = -1;
static gint ett_flightmodesettings_FlightModePosition = -1;


/* Field handles */
static int hf_op_uavobjects_flightmodesettings_ReturnToBaseAltitudeOffset = -1;
static int hf_op_uavobjects_flightmodesettings_LandingVelocity = -1;
static int hf_op_uavobjects_flightmodesettings_PositionHoldOffset = -1;
static int hf_op_uavobjects_flightmodesettings_PositionHoldOffset_Horizontal = -1;
static int hf_op_uavobjects_flightmodesettings_PositionHoldOffset_Vertical = -1;
static int hf_op_uavobjects_flightmodesettings_VarioControlLowPassAlpha = -1;
static int hf_op_uavobjects_flightmodesettings_ArmedTimeout = -1;
static int hf_op_uavobjects_flightmodesettings_ArmingSequenceTime = -1;
static int hf_op_uavobjects_flightmodesettings_DisarmingSequenceTime = -1;
static int hf_op_uavobjects_flightmodesettings_Arming = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization1Settings = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Roll = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Pitch = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Yaw = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Thrust = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization2Settings = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Roll = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Pitch = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Yaw = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Thrust = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization3Settings = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Roll = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Pitch = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Yaw = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Thrust = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization4Settings = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Roll = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Pitch = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Yaw = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Thrust = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization5Settings = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Roll = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Pitch = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Yaw = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Thrust = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization6Settings = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Roll = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Pitch = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Yaw = -1;
static int hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Thrust = -1;
static int hf_op_uavobjects_flightmodesettings_FlightModePosition = -1;
static int hf_op_uavobjects_flightmodesettings_FlightModePosition_0 = -1;
static int hf_op_uavobjects_flightmodesettings_FlightModePosition_1 = -1;
static int hf_op_uavobjects_flightmodesettings_FlightModePosition_2 = -1;
static int hf_op_uavobjects_flightmodesettings_FlightModePosition_3 = -1;
static int hf_op_uavobjects_flightmodesettings_FlightModePosition_4 = -1;
static int hf_op_uavobjects_flightmodesettings_FlightModePosition_5 = -1;
static int hf_op_uavobjects_flightmodesettings_DisableSanityChecks = -1;
static int hf_op_uavobjects_flightmodesettings_ReturnToBaseNextCommand = -1;


/* Enum string mappings */
/* Field Arming information */
/* Enumeration options for field Arming */
static const value_string uavobjects_flightmodesettings_Arming[]= {
	{ 0, "AlwaysDisarmed" },
	{ 1, "AlwaysArmed" },
	{ 2, "RollLeft" },
	{ 3, "RollRight" },
	{ 4, "PitchForward" },
	{ 5, "PitchAft" },
	{ 6, "YawLeft" },
	{ 7, "YawRight" },
	{ 8, "Accessory0" },
	{ 9, "Accessory1" },
	{ 10, "Accessory2" },
	{ 0, NULL }
};
/* Field Stabilization1Settings information */
/* Enumeration options for field Stabilization1Settings */
static const value_string uavobjects_flightmodesettings_Stabilization1Settings[]= {
	{ 0, "Manual" },
	{ 1, "Rate" },
	{ 2, "Attitude" },
	{ 3, "AxisLock" },
	{ 4, "WeakLeveling" },
	{ 5, "VirtualBar" },
	{ 6, "Acro" },
	{ 7, "Rattitude" },
	{ 8, "AltitudeHold" },
	{ 9, "AltitudeVario" },
	{ 10, "CruiseControl" },
	{ 0, NULL }
};
/* Field Stabilization2Settings information */
/* Enumeration options for field Stabilization2Settings */
static const value_string uavobjects_flightmodesettings_Stabilization2Settings[]= {
	{ 0, "Manual" },
	{ 1, "Rate" },
	{ 2, "Attitude" },
	{ 3, "AxisLock" },
	{ 4, "WeakLeveling" },
	{ 5, "VirtualBar" },
	{ 6, "Acro" },
	{ 7, "Rattitude" },
	{ 8, "AltitudeHold" },
	{ 9, "AltitudeVario" },
	{ 10, "CruiseControl" },
	{ 0, NULL }
};
/* Field Stabilization3Settings information */
/* Enumeration options for field Stabilization3Settings */
static const value_string uavobjects_flightmodesettings_Stabilization3Settings[]= {
	{ 0, "Manual" },
	{ 1, "Rate" },
	{ 2, "Attitude" },
	{ 3, "AxisLock" },
	{ 4, "WeakLeveling" },
	{ 5, "VirtualBar" },
	{ 6, "Acro" },
	{ 7, "Rattitude" },
	{ 8, "AltitudeHold" },
	{ 9, "AltitudeVario" },
	{ 10, "CruiseControl" },
	{ 0, NULL }
};
/* Field Stabilization4Settings information */
/* Enumeration options for field Stabilization4Settings */
static const value_string uavobjects_flightmodesettings_Stabilization4Settings[]= {
	{ 0, "Manual" },
	{ 1, "Rate" },
	{ 2, "Attitude" },
	{ 3, "AxisLock" },
	{ 4, "WeakLeveling" },
	{ 5, "VirtualBar" },
	{ 6, "Acro" },
	{ 7, "Rattitude" },
	{ 8, "AltitudeHold" },
	{ 9, "AltitudeVario" },
	{ 10, "CruiseControl" },
	{ 0, NULL }
};
/* Field Stabilization5Settings information */
/* Enumeration options for field Stabilization5Settings */
static const value_string uavobjects_flightmodesettings_Stabilization5Settings[]= {
	{ 0, "Manual" },
	{ 1, "Rate" },
	{ 2, "Attitude" },
	{ 3, "AxisLock" },
	{ 4, "WeakLeveling" },
	{ 5, "VirtualBar" },
	{ 6, "Acro" },
	{ 7, "Rattitude" },
	{ 8, "AltitudeHold" },
	{ 9, "AltitudeVario" },
	{ 10, "CruiseControl" },
	{ 0, NULL }
};
/* Field Stabilization6Settings information */
/* Enumeration options for field Stabilization6Settings */
static const value_string uavobjects_flightmodesettings_Stabilization6Settings[]= {
	{ 0, "Manual" },
	{ 1, "Rate" },
	{ 2, "Attitude" },
	{ 3, "AxisLock" },
	{ 4, "WeakLeveling" },
	{ 5, "VirtualBar" },
	{ 6, "Acro" },
	{ 7, "Rattitude" },
	{ 8, "AltitudeHold" },
	{ 9, "AltitudeVario" },
	{ 10, "CruiseControl" },
	{ 0, NULL }
};
/* Field FlightModePosition information */
/* Enumeration options for field FlightModePosition */
static const value_string uavobjects_flightmodesettings_FlightModePosition[]= {
	{ 0, "Manual" },
	{ 1, "Stabilized1" },
	{ 2, "Stabilized2" },
	{ 3, "Stabilized3" },
	{ 4, "Stabilized4" },
	{ 5, "Stabilized5" },
	{ 6, "Stabilized6" },
	{ 7, "PositionHold" },
	{ 8, "CourseLock" },
	{ 9, "PositionRoam" },
	{ 10, "HomeLeash" },
	{ 11, "AbsolutePosition" },
	{ 12, "ReturnToBase" },
	{ 13, "Land" },
	{ 14, "PathPlanner" },
	{ 15, "POI" },
	{ 16, "AutoCruise" },
	{ 0, NULL }
};
/* Field DisableSanityChecks information */
/* Enumeration options for field DisableSanityChecks */
static const value_string uavobjects_flightmodesettings_DisableSanityChecks[]= {
	{ 0, "FALSE" },
	{ 1, "TRUE" },
	{ 0, NULL }
};
/* Field ReturnToBaseNextCommand information */
/* Enumeration options for field ReturnToBaseNextCommand */
static const value_string uavobjects_flightmodesettings_ReturnToBaseNextCommand[]= {
	{ 0, "Hold" },
	{ 1, "Land" },
	{ 0, NULL }
};


void proto_reg_handoff_op_uavobjects_flightmodesettings(void);

static int dissect_uavo(tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree)
{
  int offset = 0;

  col_append_str(pinfo->cinfo, COL_INFO, "(FlightModeSettings)");
		  
  if (tree) { /* we are being asked for details */
    proto_tree *uavo_tree = NULL;
    ptvcursor_t * cursor;
    proto_item *ti = NULL;

    /* Add a top-level entry to the dissector tree for this protocol */
    ti = proto_tree_add_item(tree, proto_uavo, tvb, 0, -1, ENC_NA);

    /* Create a subtree to contain the dissection of this protocol */
    uavo_tree = proto_item_add_subtree(ti, ett_uavo);

    /* Dissect the packet and populate the subtree */
    cursor = ptvcursor_new(uavo_tree, tvb, 0);

    /* Populate the fields in this protocol */
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_ReturnToBaseAltitudeOffset, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_LandingVelocity, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_flightmodesettings_PositionHoldOffset, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_flightmodesettings_PositionHoldOffset);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_PositionHoldOffset_Horizontal, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_PositionHoldOffset_Vertical, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_VarioControlLowPassAlpha, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_ArmedTimeout, sizeof(guint16), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_ArmingSequenceTime, sizeof(guint16), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_DisarmingSequenceTime, sizeof(guint16), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Arming, sizeof(guint8), ENC_LITTLE_ENDIAN);
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_flightmodesettings_Stabilization1Settings, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_flightmodesettings_Stabilization1Settings);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Roll, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Pitch, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Yaw, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Thrust, sizeof(guint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_flightmodesettings_Stabilization2Settings, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_flightmodesettings_Stabilization2Settings);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Roll, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Pitch, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Yaw, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Thrust, sizeof(guint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_flightmodesettings_Stabilization3Settings, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_flightmodesettings_Stabilization3Settings);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Roll, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Pitch, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Yaw, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Thrust, sizeof(guint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_flightmodesettings_Stabilization4Settings, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_flightmodesettings_Stabilization4Settings);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Roll, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Pitch, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Yaw, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Thrust, sizeof(guint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_flightmodesettings_Stabilization5Settings, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_flightmodesettings_Stabilization5Settings);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Roll, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Pitch, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Yaw, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Thrust, sizeof(guint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_flightmodesettings_Stabilization6Settings, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_flightmodesettings_Stabilization6Settings);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Roll, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Pitch, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Yaw, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Thrust, sizeof(guint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_flightmodesettings_FlightModePosition, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_flightmodesettings_FlightModePosition);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_FlightModePosition_0, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_FlightModePosition_1, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_FlightModePosition_2, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_FlightModePosition_3, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_FlightModePosition_4, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_FlightModePosition_5, sizeof(guint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_DisableSanityChecks, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_flightmodesettings_ReturnToBaseNextCommand, sizeof(guint8), ENC_LITTLE_ENDIAN);


    offset += ptvcursor_current_offset(cursor);

    ptvcursor_free(cursor);
  } else {
    offset = 0;
  }

  return offset;
}

void proto_register_op_objects_flightmodesettings(void)
{
   static hf_register_info hf[] = {
	 { &hf_op_uavobjects_flightmodesettings_ReturnToBaseAltitudeOffset,
	   { "ReturnToBaseAltitudeOffset", "flightmodesettings.ReturnToBaseAltitudeOffset", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_LandingVelocity,
	   { "LandingVelocity", "flightmodesettings.LandingVelocity", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_PositionHoldOffset,
	   { "PositionHoldOffset", "flightmodesettings.PositionHoldOffset", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_PositionHoldOffset_Horizontal,
	   { "Horizontal", "flightmodesettings.PositionHoldOffset.Horizontal", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_PositionHoldOffset_Vertical,
	   { "Vertical", "flightmodesettings.PositionHoldOffset.Vertical", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_VarioControlLowPassAlpha,
	   { "VarioControlLowPassAlpha", "flightmodesettings.VarioControlLowPassAlpha", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_ArmedTimeout,
	   { "ArmedTimeout", "flightmodesettings.ArmedTimeout", FT_UINT16,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_ArmingSequenceTime,
	   { "ArmingSequenceTime", "flightmodesettings.ArmingSequenceTime", FT_UINT16,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_DisarmingSequenceTime,
	   { "DisarmingSequenceTime", "flightmodesettings.DisarmingSequenceTime", FT_UINT16,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Arming,
	   { "Arming", "flightmodesettings.Arming", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Arming), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization1Settings,
	   { "Stabilization1Settings", "flightmodesettings.Stabilization1Settings", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Roll,
	   { "Roll", "flightmodesettings.Stabilization1Settings.Roll", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization1Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Pitch,
	   { "Pitch", "flightmodesettings.Stabilization1Settings.Pitch", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization1Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Yaw,
	   { "Yaw", "flightmodesettings.Stabilization1Settings.Yaw", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization1Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization1Settings_Thrust,
	   { "Thrust", "flightmodesettings.Stabilization1Settings.Thrust", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization1Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization2Settings,
	   { "Stabilization2Settings", "flightmodesettings.Stabilization2Settings", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Roll,
	   { "Roll", "flightmodesettings.Stabilization2Settings.Roll", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization2Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Pitch,
	   { "Pitch", "flightmodesettings.Stabilization2Settings.Pitch", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization2Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Yaw,
	   { "Yaw", "flightmodesettings.Stabilization2Settings.Yaw", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization2Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization2Settings_Thrust,
	   { "Thrust", "flightmodesettings.Stabilization2Settings.Thrust", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization2Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization3Settings,
	   { "Stabilization3Settings", "flightmodesettings.Stabilization3Settings", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Roll,
	   { "Roll", "flightmodesettings.Stabilization3Settings.Roll", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization3Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Pitch,
	   { "Pitch", "flightmodesettings.Stabilization3Settings.Pitch", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization3Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Yaw,
	   { "Yaw", "flightmodesettings.Stabilization3Settings.Yaw", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization3Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization3Settings_Thrust,
	   { "Thrust", "flightmodesettings.Stabilization3Settings.Thrust", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization3Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization4Settings,
	   { "Stabilization4Settings", "flightmodesettings.Stabilization4Settings", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Roll,
	   { "Roll", "flightmodesettings.Stabilization4Settings.Roll", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization4Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Pitch,
	   { "Pitch", "flightmodesettings.Stabilization4Settings.Pitch", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization4Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Yaw,
	   { "Yaw", "flightmodesettings.Stabilization4Settings.Yaw", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization4Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization4Settings_Thrust,
	   { "Thrust", "flightmodesettings.Stabilization4Settings.Thrust", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization4Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization5Settings,
	   { "Stabilization5Settings", "flightmodesettings.Stabilization5Settings", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Roll,
	   { "Roll", "flightmodesettings.Stabilization5Settings.Roll", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization5Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Pitch,
	   { "Pitch", "flightmodesettings.Stabilization5Settings.Pitch", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization5Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Yaw,
	   { "Yaw", "flightmodesettings.Stabilization5Settings.Yaw", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization5Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization5Settings_Thrust,
	   { "Thrust", "flightmodesettings.Stabilization5Settings.Thrust", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization5Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization6Settings,
	   { "Stabilization6Settings", "flightmodesettings.Stabilization6Settings", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Roll,
	   { "Roll", "flightmodesettings.Stabilization6Settings.Roll", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization6Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Pitch,
	   { "Pitch", "flightmodesettings.Stabilization6Settings.Pitch", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization6Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Yaw,
	   { "Yaw", "flightmodesettings.Stabilization6Settings.Yaw", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization6Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_Stabilization6Settings_Thrust,
	   { "Thrust", "flightmodesettings.Stabilization6Settings.Thrust", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_Stabilization6Settings), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_FlightModePosition,
	   { "FlightModePosition", "flightmodesettings.FlightModePosition", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_FlightModePosition_0,
	   { "0", "flightmodesettings.FlightModePosition.0", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_FlightModePosition), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_FlightModePosition_1,
	   { "1", "flightmodesettings.FlightModePosition.1", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_FlightModePosition), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_FlightModePosition_2,
	   { "2", "flightmodesettings.FlightModePosition.2", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_FlightModePosition), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_FlightModePosition_3,
	   { "3", "flightmodesettings.FlightModePosition.3", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_FlightModePosition), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_FlightModePosition_4,
	   { "4", "flightmodesettings.FlightModePosition.4", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_FlightModePosition), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_FlightModePosition_5,
	   { "5", "flightmodesettings.FlightModePosition.5", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_FlightModePosition), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_DisableSanityChecks,
	   { "DisableSanityChecks", "flightmodesettings.DisableSanityChecks", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_DisableSanityChecks), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_flightmodesettings_ReturnToBaseNextCommand,
	   { "ReturnToBaseNextCommand", "flightmodesettings.ReturnToBaseNextCommand", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_flightmodesettings_ReturnToBaseNextCommand), 0x0, NULL, HFILL 
	   },
	 },
   };


   /* Setup protocol subtree array */

   static gint *ett[] = {
	&ett_uavo,
&ett_flightmodesettings_PositionHoldOffset,
&ett_flightmodesettings_Stabilization1Settings,
&ett_flightmodesettings_Stabilization2Settings,
&ett_flightmodesettings_Stabilization3Settings,
&ett_flightmodesettings_Stabilization4Settings,
&ett_flightmodesettings_Stabilization5Settings,
&ett_flightmodesettings_Stabilization6Settings,
&ett_flightmodesettings_FlightModePosition,

   };

   /* Register this protocol */
   proto_uavo = proto_register_protocol("UAVO FlightModeSettings", 
				   "UAVO FlightModeSettings", 
				   "uavo-flightmodesettings");

   /* Register the field definitions for this protocol */
   proto_register_subtree_array(ett, array_length(ett));
   proto_register_field_array(proto_uavo, hf, array_length(hf));
}

void proto_reg_handoff_op_uavobjects_flightmodesettings(void)
{
   dissector_handle_t uavo_handle;
   uavo_handle = new_create_dissector_handle(dissect_uavo, proto_uavo);

   /* Bind this protocol to its UAV ObjID in UAVTalk */
   dissector_add("uavtalk.objid", 0x22D6BC8, uavo_handle);
}
