/*
  * !!! Autogenerated from stabilizationbank.xml Do NOT Edit !!!
  *
  * Routines for OpenPilot UAVObject dissection
  * Copyright 2012 Stacey Sheldon <stac@solidgoldbomb.org>
  *
  * $Id$
  *
  * Wireshark - Network traffic analyzer
  * By Gerald Combs <gerald@wireshark.org>
  * Copyright 1998 Gerald Combs
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU General Public License
  * as published by the Free Software Foundation; either version 2
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program; if not, write to the Free Software
  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <epan/packet.h>
#include <epan/ptvcursor.h>	/* ptvcursor_* */

#include <glib.h>
#include <string.h>

static int proto_uavo = -1;

/* Subtree expansion tracking */
static gint ett_uavo = -1;
static gint ett_stabilizationbank_ManualRate = -1;
static gint ett_stabilizationbank_MaximumRate = -1;
static gint ett_stabilizationbank_RollRatePID = -1;
static gint ett_stabilizationbank_PitchRatePID = -1;
static gint ett_stabilizationbank_YawRatePID = -1;
static gint ett_stabilizationbank_RollPI = -1;
static gint ett_stabilizationbank_PitchPI = -1;
static gint ett_stabilizationbank_YawPI = -1;
static gint ett_stabilizationbank_ThrustPIDScaleCurve = -1;
static gint ett_stabilizationbank_StickExpo = -1;


/* Field handles */
static int hf_op_uavobjects_stabilizationbank_ManualRate = -1;
static int hf_op_uavobjects_stabilizationbank_ManualRate_Roll = -1;
static int hf_op_uavobjects_stabilizationbank_ManualRate_Pitch = -1;
static int hf_op_uavobjects_stabilizationbank_ManualRate_Yaw = -1;
static int hf_op_uavobjects_stabilizationbank_MaximumRate = -1;
static int hf_op_uavobjects_stabilizationbank_MaximumRate_Roll = -1;
static int hf_op_uavobjects_stabilizationbank_MaximumRate_Pitch = -1;
static int hf_op_uavobjects_stabilizationbank_MaximumRate_Yaw = -1;
static int hf_op_uavobjects_stabilizationbank_RollRatePID = -1;
static int hf_op_uavobjects_stabilizationbank_RollRatePID_Kp = -1;
static int hf_op_uavobjects_stabilizationbank_RollRatePID_Ki = -1;
static int hf_op_uavobjects_stabilizationbank_RollRatePID_Kd = -1;
static int hf_op_uavobjects_stabilizationbank_RollRatePID_ILimit = -1;
static int hf_op_uavobjects_stabilizationbank_PitchRatePID = -1;
static int hf_op_uavobjects_stabilizationbank_PitchRatePID_Kp = -1;
static int hf_op_uavobjects_stabilizationbank_PitchRatePID_Ki = -1;
static int hf_op_uavobjects_stabilizationbank_PitchRatePID_Kd = -1;
static int hf_op_uavobjects_stabilizationbank_PitchRatePID_ILimit = -1;
static int hf_op_uavobjects_stabilizationbank_YawRatePID = -1;
static int hf_op_uavobjects_stabilizationbank_YawRatePID_Kp = -1;
static int hf_op_uavobjects_stabilizationbank_YawRatePID_Ki = -1;
static int hf_op_uavobjects_stabilizationbank_YawRatePID_Kd = -1;
static int hf_op_uavobjects_stabilizationbank_YawRatePID_ILimit = -1;
static int hf_op_uavobjects_stabilizationbank_RollPI = -1;
static int hf_op_uavobjects_stabilizationbank_RollPI_Kp = -1;
static int hf_op_uavobjects_stabilizationbank_RollPI_Ki = -1;
static int hf_op_uavobjects_stabilizationbank_RollPI_ILimit = -1;
static int hf_op_uavobjects_stabilizationbank_PitchPI = -1;
static int hf_op_uavobjects_stabilizationbank_PitchPI_Kp = -1;
static int hf_op_uavobjects_stabilizationbank_PitchPI_Ki = -1;
static int hf_op_uavobjects_stabilizationbank_PitchPI_ILimit = -1;
static int hf_op_uavobjects_stabilizationbank_YawPI = -1;
static int hf_op_uavobjects_stabilizationbank_YawPI_Kp = -1;
static int hf_op_uavobjects_stabilizationbank_YawPI_Ki = -1;
static int hf_op_uavobjects_stabilizationbank_YawPI_ILimit = -1;
static int hf_op_uavobjects_stabilizationbank_AcroInsanityFactor = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_0 = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_25 = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_50 = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_75 = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_100 = -1;
static int hf_op_uavobjects_stabilizationbank_RollMax = -1;
static int hf_op_uavobjects_stabilizationbank_PitchMax = -1;
static int hf_op_uavobjects_stabilizationbank_YawMax = -1;
static int hf_op_uavobjects_stabilizationbank_StickExpo = -1;
static int hf_op_uavobjects_stabilizationbank_StickExpo_Roll = -1;
static int hf_op_uavobjects_stabilizationbank_StickExpo_Pitch = -1;
static int hf_op_uavobjects_stabilizationbank_StickExpo_Yaw = -1;
static int hf_op_uavobjects_stabilizationbank_EnablePiroComp = -1;
static int hf_op_uavobjects_stabilizationbank_EnableThrustPIDScaling = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleSource = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleTarget = -1;
static int hf_op_uavobjects_stabilizationbank_ThrustPIDScaleAxes = -1;


/* Enum string mappings */
/* Field EnablePiroComp information */
/* Enumeration options for field EnablePiroComp */
static const value_string uavobjects_stabilizationbank_EnablePiroComp[]= {
	{ 0, "FALSE" },
	{ 1, "TRUE" },
	{ 0, NULL }
};
/* Field EnableThrustPIDScaling information */
/* Enumeration options for field EnableThrustPIDScaling */
static const value_string uavobjects_stabilizationbank_EnableThrustPIDScaling[]= {
	{ 0, "FALSE" },
	{ 1, "TRUE" },
	{ 0, NULL }
};
/* Field ThrustPIDScaleSource information */
/* Enumeration options for field ThrustPIDScaleSource */
static const value_string uavobjects_stabilizationbank_ThrustPIDScaleSource[]= {
	{ 0, "ManualControlThrottle" },
	{ 1, "StabilizationDesiredThrust" },
	{ 2, "ActuatorDesiredThrust" },
	{ 0, NULL }
};
/* Field ThrustPIDScaleTarget information */
/* Enumeration options for field ThrustPIDScaleTarget */
static const value_string uavobjects_stabilizationbank_ThrustPIDScaleTarget[]= {
	{ 0, "PID" },
	{ 1, "PI" },
	{ 2, "PD" },
	{ 3, "ID" },
	{ 4, "P" },
	{ 5, "I" },
	{ 6, "D" },
	{ 0, NULL }
};
/* Field ThrustPIDScaleAxes information */
/* Enumeration options for field ThrustPIDScaleAxes */
static const value_string uavobjects_stabilizationbank_ThrustPIDScaleAxes[]= {
	{ 0, "RollPitchYaw" },
	{ 1, "RollPitch" },
	{ 2, "RollYaw" },
	{ 3, "Roll" },
	{ 4, "PitchYaw" },
	{ 5, "Pitch" },
	{ 6, "Yaw" },
	{ 0, NULL }
};


void proto_reg_handoff_op_uavobjects_stabilizationbank(void);

static int dissect_uavo(tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree)
{
  int offset = 0;

  col_append_str(pinfo->cinfo, COL_INFO, "(StabilizationBank)");
		  
  if (tree) { /* we are being asked for details */
    proto_tree *uavo_tree = NULL;
    ptvcursor_t * cursor;
    proto_item *ti = NULL;

    /* Add a top-level entry to the dissector tree for this protocol */
    ti = proto_tree_add_item(tree, proto_uavo, tvb, 0, -1, ENC_NA);

    /* Create a subtree to contain the dissection of this protocol */
    uavo_tree = proto_item_add_subtree(ti, ett_uavo);

    /* Dissect the packet and populate the subtree */
    cursor = ptvcursor_new(uavo_tree, tvb, 0);

    /* Populate the fields in this protocol */
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_ManualRate, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_ManualRate);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ManualRate_Roll, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ManualRate_Pitch, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ManualRate_Yaw, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_MaximumRate, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_MaximumRate);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_MaximumRate_Roll, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_MaximumRate_Pitch, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_MaximumRate_Yaw, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_RollRatePID, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_RollRatePID);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_RollRatePID_Kp, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_RollRatePID_Ki, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_RollRatePID_Kd, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_RollRatePID_ILimit, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_PitchRatePID, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_PitchRatePID);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_PitchRatePID_Kp, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_PitchRatePID_Ki, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_PitchRatePID_Kd, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_PitchRatePID_ILimit, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_YawRatePID, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_YawRatePID);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_YawRatePID_Kp, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_YawRatePID_Ki, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_YawRatePID_Kd, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_YawRatePID_ILimit, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_RollPI, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_RollPI);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_RollPI_Kp, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_RollPI_Ki, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_RollPI_ILimit, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_PitchPI, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_PitchPI);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_PitchPI_Kp, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_PitchPI_Ki, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_PitchPI_ILimit, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_YawPI, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_YawPI);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_YawPI_Kp, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_YawPI_Ki, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_YawPI_ILimit, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_AcroInsanityFactor, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_ThrustPIDScaleCurve);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_0, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_25, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_50, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_75, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_100, sizeof(gfloat), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_RollMax, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_PitchMax, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_YawMax, sizeof(guint8), ENC_LITTLE_ENDIAN);
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_stabilizationbank_StickExpo, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_stabilizationbank_StickExpo);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_StickExpo_Roll, sizeof(gint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_StickExpo_Pitch, sizeof(gint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_StickExpo_Yaw, sizeof(gint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_EnablePiroComp, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_EnableThrustPIDScaling, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleSource, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleTarget, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_stabilizationbank_ThrustPIDScaleAxes, sizeof(guint8), ENC_LITTLE_ENDIAN);


    offset += ptvcursor_current_offset(cursor);

    ptvcursor_free(cursor);
  } else {
    offset = 0;
  }

  return offset;
}

void proto_register_op_objects_stabilizationbank(void)
{
   static hf_register_info hf[] = {
	 { &hf_op_uavobjects_stabilizationbank_ManualRate,
	   { "ManualRate", "stabilizationbank.ManualRate", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ManualRate_Roll,
	   { "Roll", "stabilizationbank.ManualRate.Roll", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ManualRate_Pitch,
	   { "Pitch", "stabilizationbank.ManualRate.Pitch", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ManualRate_Yaw,
	   { "Yaw", "stabilizationbank.ManualRate.Yaw", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_MaximumRate,
	   { "MaximumRate", "stabilizationbank.MaximumRate", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_MaximumRate_Roll,
	   { "Roll", "stabilizationbank.MaximumRate.Roll", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_MaximumRate_Pitch,
	   { "Pitch", "stabilizationbank.MaximumRate.Pitch", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_MaximumRate_Yaw,
	   { "Yaw", "stabilizationbank.MaximumRate.Yaw", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollRatePID,
	   { "RollRatePID", "stabilizationbank.RollRatePID", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollRatePID_Kp,
	   { "Kp", "stabilizationbank.RollRatePID.Kp", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollRatePID_Ki,
	   { "Ki", "stabilizationbank.RollRatePID.Ki", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollRatePID_Kd,
	   { "Kd", "stabilizationbank.RollRatePID.Kd", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollRatePID_ILimit,
	   { "ILimit", "stabilizationbank.RollRatePID.ILimit", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchRatePID,
	   { "PitchRatePID", "stabilizationbank.PitchRatePID", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchRatePID_Kp,
	   { "Kp", "stabilizationbank.PitchRatePID.Kp", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchRatePID_Ki,
	   { "Ki", "stabilizationbank.PitchRatePID.Ki", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchRatePID_Kd,
	   { "Kd", "stabilizationbank.PitchRatePID.Kd", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchRatePID_ILimit,
	   { "ILimit", "stabilizationbank.PitchRatePID.ILimit", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawRatePID,
	   { "YawRatePID", "stabilizationbank.YawRatePID", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawRatePID_Kp,
	   { "Kp", "stabilizationbank.YawRatePID.Kp", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawRatePID_Ki,
	   { "Ki", "stabilizationbank.YawRatePID.Ki", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawRatePID_Kd,
	   { "Kd", "stabilizationbank.YawRatePID.Kd", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawRatePID_ILimit,
	   { "ILimit", "stabilizationbank.YawRatePID.ILimit", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollPI,
	   { "RollPI", "stabilizationbank.RollPI", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollPI_Kp,
	   { "Kp", "stabilizationbank.RollPI.Kp", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollPI_Ki,
	   { "Ki", "stabilizationbank.RollPI.Ki", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollPI_ILimit,
	   { "ILimit", "stabilizationbank.RollPI.ILimit", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchPI,
	   { "PitchPI", "stabilizationbank.PitchPI", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchPI_Kp,
	   { "Kp", "stabilizationbank.PitchPI.Kp", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchPI_Ki,
	   { "Ki", "stabilizationbank.PitchPI.Ki", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchPI_ILimit,
	   { "ILimit", "stabilizationbank.PitchPI.ILimit", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawPI,
	   { "YawPI", "stabilizationbank.YawPI", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawPI_Kp,
	   { "Kp", "stabilizationbank.YawPI.Kp", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawPI_Ki,
	   { "Ki", "stabilizationbank.YawPI.Ki", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawPI_ILimit,
	   { "ILimit", "stabilizationbank.YawPI.ILimit", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_AcroInsanityFactor,
	   { "AcroInsanityFactor", "stabilizationbank.AcroInsanityFactor", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve,
	   { "ThrustPIDScaleCurve", "stabilizationbank.ThrustPIDScaleCurve", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_0,
	   { "0", "stabilizationbank.ThrustPIDScaleCurve.0", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_25,
	   { "25", "stabilizationbank.ThrustPIDScaleCurve.25", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_50,
	   { "50", "stabilizationbank.ThrustPIDScaleCurve.50", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_75,
	   { "75", "stabilizationbank.ThrustPIDScaleCurve.75", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleCurve_100,
	   { "100", "stabilizationbank.ThrustPIDScaleCurve.100", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_RollMax,
	   { "RollMax", "stabilizationbank.RollMax", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_PitchMax,
	   { "PitchMax", "stabilizationbank.PitchMax", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_YawMax,
	   { "YawMax", "stabilizationbank.YawMax", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_StickExpo,
	   { "StickExpo", "stabilizationbank.StickExpo", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_StickExpo_Roll,
	   { "Roll", "stabilizationbank.StickExpo.Roll", FT_INT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_StickExpo_Pitch,
	   { "Pitch", "stabilizationbank.StickExpo.Pitch", FT_INT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_StickExpo_Yaw,
	   { "Yaw", "stabilizationbank.StickExpo.Yaw", FT_INT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_EnablePiroComp,
	   { "EnablePiroComp", "stabilizationbank.EnablePiroComp", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_stabilizationbank_EnablePiroComp), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_EnableThrustPIDScaling,
	   { "EnableThrustPIDScaling", "stabilizationbank.EnableThrustPIDScaling", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_stabilizationbank_EnableThrustPIDScaling), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleSource,
	   { "ThrustPIDScaleSource", "stabilizationbank.ThrustPIDScaleSource", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_stabilizationbank_ThrustPIDScaleSource), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleTarget,
	   { "ThrustPIDScaleTarget", "stabilizationbank.ThrustPIDScaleTarget", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_stabilizationbank_ThrustPIDScaleTarget), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_stabilizationbank_ThrustPIDScaleAxes,
	   { "ThrustPIDScaleAxes", "stabilizationbank.ThrustPIDScaleAxes", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_stabilizationbank_ThrustPIDScaleAxes), 0x0, NULL, HFILL 
	   },
	 },
   };


   /* Setup protocol subtree array */

   static gint *ett[] = {
	&ett_uavo,
&ett_stabilizationbank_ManualRate,
&ett_stabilizationbank_MaximumRate,
&ett_stabilizationbank_RollRatePID,
&ett_stabilizationbank_PitchRatePID,
&ett_stabilizationbank_YawRatePID,
&ett_stabilizationbank_RollPI,
&ett_stabilizationbank_PitchPI,
&ett_stabilizationbank_YawPI,
&ett_stabilizationbank_ThrustPIDScaleCurve,
&ett_stabilizationbank_StickExpo,

   };

   /* Register this protocol */
   proto_uavo = proto_register_protocol("UAVO StabilizationBank", 
				   "UAVO StabilizationBank", 
				   "uavo-stabilizationbank");

   /* Register the field definitions for this protocol */
   proto_register_subtree_array(ett, array_length(ett));
   proto_register_field_array(proto_uavo, hf, array_length(hf));
}

void proto_reg_handoff_op_uavobjects_stabilizationbank(void)
{
   dissector_handle_t uavo_handle;
   uavo_handle = new_create_dissector_handle(dissect_uavo, proto_uavo);

   /* Bind this protocol to its UAV ObjID in UAVTalk */
   dissector_add("uavtalk.objid", 0xE6EE9106, uavo_handle);
}
