/*
  * !!! Autogenerated from gpssettings.xml Do NOT Edit !!!
  *
  * Routines for OpenPilot UAVObject dissection
  * Copyright 2012 Stacey Sheldon <stac@solidgoldbomb.org>
  *
  * $Id$
  *
  * Wireshark - Network traffic analyzer
  * By Gerald Combs <gerald@wireshark.org>
  * Copyright 1998 Gerald Combs
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU General Public License
  * as published by the Free Software Foundation; either version 2
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program; if not, write to the Free Software
  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <epan/packet.h>
#include <epan/ptvcursor.h>	/* ptvcursor_* */

#include <glib.h>
#include <string.h>

static int proto_uavo = -1;

/* Subtree expansion tracking */
static gint ett_uavo = -1;


/* Field handles */
static int hf_op_uavobjects_gpssettings_MaxPDOP = -1;
static int hf_op_uavobjects_gpssettings_DataProtocol = -1;
static int hf_op_uavobjects_gpssettings_MinSatellites = -1;
static int hf_op_uavobjects_gpssettings_UbxAutoConfig = -1;
static int hf_op_uavobjects_gpssettings_UbxRate = -1;
static int hf_op_uavobjects_gpssettings_UbxDynamicModel = -1;
static int hf_op_uavobjects_gpssettings_UbxSBASMode = -1;
static int hf_op_uavobjects_gpssettings_UbxSBASChannelsUsed = -1;
static int hf_op_uavobjects_gpssettings_UbxSBASSats = -1;
static int hf_op_uavobjects_gpssettings_UbxGNSSMode = -1;


/* Enum string mappings */
/* Field DataProtocol information */
/* Enumeration options for field DataProtocol */
static const value_string uavobjects_gpssettings_DataProtocol[]= {
	{ 0, "NMEA" },
	{ 1, "UBX" },
	{ 0, NULL }
};
/* Field UbxAutoConfig information */
/* Enumeration options for field UbxAutoConfig */
static const value_string uavobjects_gpssettings_UbxAutoConfig[]= {
	{ 0, "Disabled" },
	{ 1, "Configure" },
	{ 2, "ConfigureAndStore" },
	{ 0, NULL }
};
/* Field UbxDynamicModel information */
/* Enumeration options for field UbxDynamicModel */
static const value_string uavobjects_gpssettings_UbxDynamicModel[]= {
	{ 0, "Portable" },
	{ 1, "Stationary" },
	{ 2, "Pedestrian" },
	{ 3, "Automotive" },
	{ 4, "Sea" },
	{ 5, "Airborne1G" },
	{ 6, "Airborne2G" },
	{ 7, "Airborne4G" },
	{ 0, NULL }
};
/* Field UbxSBASMode information */
/* Enumeration options for field UbxSBASMode */
static const value_string uavobjects_gpssettings_UbxSBASMode[]= {
	{ 0, "Disabled" },
	{ 1, "Ranging" },
	{ 2, "Correction" },
	{ 3, "Integrity" },
	{ 4, "RangingCorrection" },
	{ 5, "RangingIntegrity" },
	{ 6, "RangingCorrectionIntegrity" },
	{ 7, "CorrectionIntegrity" },
	{ 0, NULL }
};
/* Field UbxSBASSats information */
/* Enumeration options for field UbxSBASSats */
static const value_string uavobjects_gpssettings_UbxSBASSats[]= {
	{ 0, "AutoScan" },
	{ 1, "WAAS" },
	{ 2, "EGNOS" },
	{ 3, "MSAS" },
	{ 4, "GAGAN" },
	{ 5, "SDCM" },
	{ 0, NULL }
};
/* Field UbxGNSSMode information */
/* Enumeration options for field UbxGNSSMode */
static const value_string uavobjects_gpssettings_UbxGNSSMode[]= {
	{ 0, "Default" },
	{ 1, "GPS" },
	{ 2, "GLONASS" },
	{ 3, "GPSGLONASS" },
	{ 4, "GPSBeiDou" },
	{ 5, "GLONASSBeiDou" },
	{ 0, NULL }
};


void proto_reg_handoff_op_uavobjects_gpssettings(void);

static int dissect_uavo(tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree)
{
  int offset = 0;

  col_append_str(pinfo->cinfo, COL_INFO, "(GPSSettings)");
		  
  if (tree) { /* we are being asked for details */
    proto_tree *uavo_tree = NULL;
    ptvcursor_t * cursor;
    proto_item *ti = NULL;

    /* Add a top-level entry to the dissector tree for this protocol */
    ti = proto_tree_add_item(tree, proto_uavo, tvb, 0, -1, ENC_NA);

    /* Create a subtree to contain the dissection of this protocol */
    uavo_tree = proto_item_add_subtree(ti, ett_uavo);

    /* Dissect the packet and populate the subtree */
    cursor = ptvcursor_new(uavo_tree, tvb, 0);

    /* Populate the fields in this protocol */
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_MaxPDOP, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_DataProtocol, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_MinSatellites, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_UbxAutoConfig, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_UbxRate, sizeof(gint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_UbxDynamicModel, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_UbxSBASMode, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_UbxSBASChannelsUsed, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_UbxSBASSats, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpssettings_UbxGNSSMode, sizeof(guint8), ENC_LITTLE_ENDIAN);


    offset += ptvcursor_current_offset(cursor);

    ptvcursor_free(cursor);
  } else {
    offset = 0;
  }

  return offset;
}

void proto_register_op_objects_gpssettings(void)
{
   static hf_register_info hf[] = {
	 { &hf_op_uavobjects_gpssettings_MaxPDOP,
	   { "MaxPDOP", "gpssettings.MaxPDOP", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_DataProtocol,
	   { "DataProtocol", "gpssettings.DataProtocol", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpssettings_DataProtocol), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_MinSatellites,
	   { "MinSatellites", "gpssettings.MinSatellites", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_UbxAutoConfig,
	   { "UbxAutoConfig", "gpssettings.UbxAutoConfig", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpssettings_UbxAutoConfig), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_UbxRate,
	   { "UbxRate", "gpssettings.UbxRate", FT_INT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_UbxDynamicModel,
	   { "UbxDynamicModel", "gpssettings.UbxDynamicModel", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpssettings_UbxDynamicModel), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_UbxSBASMode,
	   { "UbxSBASMode", "gpssettings.UbxSBASMode", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpssettings_UbxSBASMode), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_UbxSBASChannelsUsed,
	   { "UbxSBASChannelsUsed", "gpssettings.UbxSBASChannelsUsed", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_UbxSBASSats,
	   { "UbxSBASSats", "gpssettings.UbxSBASSats", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpssettings_UbxSBASSats), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpssettings_UbxGNSSMode,
	   { "UbxGNSSMode", "gpssettings.UbxGNSSMode", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpssettings_UbxGNSSMode), 0x0, NULL, HFILL 
	   },
	 },
   };


   /* Setup protocol subtree array */

   static gint *ett[] = {
	&ett_uavo,

   };

   /* Register this protocol */
   proto_uavo = proto_register_protocol("UAVO GPSSettings", 
				   "UAVO GPSSettings", 
				   "uavo-gpssettings");

   /* Register the field definitions for this protocol */
   proto_register_subtree_array(ett, array_length(ett));
   proto_register_field_array(proto_uavo, hf, array_length(hf));
}

void proto_reg_handoff_op_uavobjects_gpssettings(void)
{
   dissector_handle_t uavo_handle;
   uavo_handle = new_create_dissector_handle(dissect_uavo, proto_uavo);

   /* Bind this protocol to its UAV ObjID in UAVTalk */
   dissector_add("uavtalk.objid", 0x70C7BC8E, uavo_handle);
}
