/*
  * !!! Autogenerated from systemsettings.xml Do NOT Edit !!!
  *
  * Routines for OpenPilot UAVObject dissection
  * Copyright 2012 Stacey Sheldon <stac@solidgoldbomb.org>
  *
  * $Id$
  *
  * Wireshark - Network traffic analyzer
  * By Gerald Combs <gerald@wireshark.org>
  * Copyright 1998 Gerald Combs
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU General Public License
  * as published by the Free Software Foundation; either version 2
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program; if not, write to the Free Software
  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <epan/packet.h>
#include <epan/ptvcursor.h>	/* ptvcursor_* */

#include <glib.h>
#include <string.h>

static int proto_uavo = -1;

/* Subtree expansion tracking */
static gint ett_uavo = -1;
static gint ett_systemsettings_GUIConfigData = -1;
static gint ett_systemsettings_VehicleName = -1;


/* Field handles */
static int hf_op_uavobjects_systemsettings_GUIConfigData = -1;
static int hf_op_uavobjects_systemsettings_GUIConfigData_0 = -1;
static int hf_op_uavobjects_systemsettings_GUIConfigData_1 = -1;
static int hf_op_uavobjects_systemsettings_GUIConfigData_2 = -1;
static int hf_op_uavobjects_systemsettings_GUIConfigData_3 = -1;
static int hf_op_uavobjects_systemsettings_AirSpeedMax = -1;
static int hf_op_uavobjects_systemsettings_AirSpeedMin = -1;
static int hf_op_uavobjects_systemsettings_AirframeType = -1;
static int hf_op_uavobjects_systemsettings_VehicleName = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_0 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_1 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_2 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_3 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_4 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_5 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_6 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_7 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_8 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_9 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_10 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_11 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_12 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_13 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_14 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_15 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_16 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_17 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_18 = -1;
static int hf_op_uavobjects_systemsettings_VehicleName_19 = -1;
static int hf_op_uavobjects_systemsettings_ThrustControl = -1;


/* Enum string mappings */
/* Field AirframeType information */
/* Enumeration options for field AirframeType */
static const value_string uavobjects_systemsettings_AirframeType[]= {
	{ 0, "FixedWing" },
	{ 1, "FixedWingElevon" },
	{ 2, "FixedWingVtail" },
	{ 3, "VTOL" },
	{ 4, "HeliCP" },
	{ 5, "QuadX" },
	{ 6, "QuadP" },
	{ 7, "Hexa" },
	{ 8, "Octo" },
	{ 9, "Custom" },
	{ 10, "HexaX" },
	{ 11, "HexaH" },
	{ 12, "OctoV" },
	{ 13, "OctoCoaxP" },
	{ 14, "OctoCoaxX" },
	{ 15, "OctoX" },
	{ 16, "HexaCoax" },
	{ 17, "Tri" },
	{ 18, "GroundVehicleCar" },
	{ 19, "GroundVehicleDifferential" },
	{ 20, "GroundVehicleMotorcycle" },
	{ 0, NULL }
};
/* Field ThrustControl information */
/* Enumeration options for field ThrustControl */
static const value_string uavobjects_systemsettings_ThrustControl[]= {
	{ 0, "Throttle" },
	{ 1, "Collective" },
	{ 2, "None" },
	{ 0, NULL }
};


void proto_reg_handoff_op_uavobjects_systemsettings(void);

static int dissect_uavo(tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree)
{
  int offset = 0;

  col_append_str(pinfo->cinfo, COL_INFO, "(SystemSettings)");
		  
  if (tree) { /* we are being asked for details */
    proto_tree *uavo_tree = NULL;
    ptvcursor_t * cursor;
    proto_item *ti = NULL;

    /* Add a top-level entry to the dissector tree for this protocol */
    ti = proto_tree_add_item(tree, proto_uavo, tvb, 0, -1, ENC_NA);

    /* Create a subtree to contain the dissection of this protocol */
    uavo_tree = proto_item_add_subtree(ti, ett_uavo);

    /* Dissect the packet and populate the subtree */
    cursor = ptvcursor_new(uavo_tree, tvb, 0);

    /* Populate the fields in this protocol */
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_systemsettings_GUIConfigData, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_systemsettings_GUIConfigData);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_GUIConfigData_0, sizeof(guint32), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_GUIConfigData_1, sizeof(guint32), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_GUIConfigData_2, sizeof(guint32), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_GUIConfigData_3, sizeof(guint32), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_AirSpeedMax, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_AirSpeedMin, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_AirframeType, sizeof(guint8), ENC_LITTLE_ENDIAN);
    {
      proto_item * it = NULL;
      it = ptvcursor_add_no_advance(cursor, hf_op_uavobjects_systemsettings_VehicleName, 1, ENC_NA);
      ptvcursor_push_subtree(cursor, it, ett_systemsettings_VehicleName);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_0, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_1, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_2, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_3, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_4, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_5, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_6, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_7, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_8, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_9, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_10, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_11, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_12, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_13, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_14, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_15, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_16, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_17, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_18, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_VehicleName_19, sizeof(guint8), ENC_LITTLE_ENDIAN);
      ptvcursor_pop_subtree(cursor);
    }
    ptvcursor_add(cursor, hf_op_uavobjects_systemsettings_ThrustControl, sizeof(guint8), ENC_LITTLE_ENDIAN);


    offset += ptvcursor_current_offset(cursor);

    ptvcursor_free(cursor);
  } else {
    offset = 0;
  }

  return offset;
}

void proto_register_op_objects_systemsettings(void)
{
   static hf_register_info hf[] = {
	 { &hf_op_uavobjects_systemsettings_GUIConfigData,
	   { "GUIConfigData", "systemsettings.GUIConfigData", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_GUIConfigData_0,
	   { "0", "systemsettings.GUIConfigData.0", FT_UINT32,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_GUIConfigData_1,
	   { "1", "systemsettings.GUIConfigData.1", FT_UINT32,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_GUIConfigData_2,
	   { "2", "systemsettings.GUIConfigData.2", FT_UINT32,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_GUIConfigData_3,
	   { "3", "systemsettings.GUIConfigData.3", FT_UINT32,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_AirSpeedMax,
	   { "AirSpeedMax", "systemsettings.AirSpeedMax", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_AirSpeedMin,
	   { "AirSpeedMin", "systemsettings.AirSpeedMin", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_AirframeType,
	   { "AirframeType", "systemsettings.AirframeType", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_systemsettings_AirframeType), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName,
	   { "VehicleName", "systemsettings.VehicleName", FT_NONE,
	     BASE_NONE, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_0,
	   { "0", "systemsettings.VehicleName.0", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_1,
	   { "1", "systemsettings.VehicleName.1", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_2,
	   { "2", "systemsettings.VehicleName.2", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_3,
	   { "3", "systemsettings.VehicleName.3", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_4,
	   { "4", "systemsettings.VehicleName.4", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_5,
	   { "5", "systemsettings.VehicleName.5", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_6,
	   { "6", "systemsettings.VehicleName.6", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_7,
	   { "7", "systemsettings.VehicleName.7", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_8,
	   { "8", "systemsettings.VehicleName.8", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_9,
	   { "9", "systemsettings.VehicleName.9", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_10,
	   { "10", "systemsettings.VehicleName.10", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_11,
	   { "11", "systemsettings.VehicleName.11", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_12,
	   { "12", "systemsettings.VehicleName.12", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_13,
	   { "13", "systemsettings.VehicleName.13", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_14,
	   { "14", "systemsettings.VehicleName.14", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_15,
	   { "15", "systemsettings.VehicleName.15", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_16,
	   { "16", "systemsettings.VehicleName.16", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_17,
	   { "17", "systemsettings.VehicleName.17", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_18,
	   { "18", "systemsettings.VehicleName.18", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_VehicleName_19,
	   { "19", "systemsettings.VehicleName.19", FT_UINT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_systemsettings_ThrustControl,
	   { "ThrustControl", "systemsettings.ThrustControl", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_systemsettings_ThrustControl), 0x0, NULL, HFILL 
	   },
	 },
   };


   /* Setup protocol subtree array */

   static gint *ett[] = {
	&ett_uavo,
&ett_systemsettings_GUIConfigData,
&ett_systemsettings_VehicleName,

   };

   /* Register this protocol */
   proto_uavo = proto_register_protocol("UAVO SystemSettings", 
				   "UAVO SystemSettings", 
				   "uavo-systemsettings");

   /* Register the field definitions for this protocol */
   proto_register_subtree_array(ett, array_length(ett));
   proto_register_field_array(proto_uavo, hf, array_length(hf));
}

void proto_reg_handoff_op_uavobjects_systemsettings(void)
{
   dissector_handle_t uavo_handle;
   uavo_handle = new_create_dissector_handle(dissect_uavo, proto_uavo);

   /* Bind this protocol to its UAV ObjID in UAVTalk */
   dissector_add("uavtalk.objid", 0xD9D093B8, uavo_handle);
}
