/*
  * !!! Autogenerated from gpspositionsensor.xml Do NOT Edit !!!
  *
  * Routines for OpenPilot UAVObject dissection
  * Copyright 2012 Stacey Sheldon <stac@solidgoldbomb.org>
  *
  * $Id$
  *
  * Wireshark - Network traffic analyzer
  * By Gerald Combs <gerald@wireshark.org>
  * Copyright 1998 Gerald Combs
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU General Public License
  * as published by the Free Software Foundation; either version 2
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program; if not, write to the Free Software
  * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include <epan/packet.h>
#include <epan/ptvcursor.h>	/* ptvcursor_* */

#include <glib.h>
#include <string.h>

static int proto_uavo = -1;

/* Subtree expansion tracking */
static gint ett_uavo = -1;


/* Field handles */
static int hf_op_uavobjects_gpspositionsensor_Latitude = -1;
static int hf_op_uavobjects_gpspositionsensor_Longitude = -1;
static int hf_op_uavobjects_gpspositionsensor_Altitude = -1;
static int hf_op_uavobjects_gpspositionsensor_GeoidSeparation = -1;
static int hf_op_uavobjects_gpspositionsensor_Heading = -1;
static int hf_op_uavobjects_gpspositionsensor_Groundspeed = -1;
static int hf_op_uavobjects_gpspositionsensor_PDOP = -1;
static int hf_op_uavobjects_gpspositionsensor_HDOP = -1;
static int hf_op_uavobjects_gpspositionsensor_VDOP = -1;
static int hf_op_uavobjects_gpspositionsensor_Status = -1;
static int hf_op_uavobjects_gpspositionsensor_Satellites = -1;
static int hf_op_uavobjects_gpspositionsensor_SensorType = -1;
static int hf_op_uavobjects_gpspositionsensor_AutoConfigStatus = -1;


/* Enum string mappings */
/* Field Status information */
/* Enumeration options for field Status */
static const value_string uavobjects_gpspositionsensor_Status[]= {
	{ 0, "NoGPS" },
	{ 1, "NoFix" },
	{ 2, "Fix2D" },
	{ 3, "Fix3D" },
	{ 0, NULL }
};
/* Field SensorType information */
/* Enumeration options for field SensorType */
static const value_string uavobjects_gpspositionsensor_SensorType[]= {
	{ 0, "Unknown" },
	{ 1, "NMEA" },
	{ 2, "UBX" },
	{ 3, "UBX7" },
	{ 4, "UBX8" },
	{ 0, NULL }
};
/* Field AutoConfigStatus information */
/* Enumeration options for field AutoConfigStatus */
static const value_string uavobjects_gpspositionsensor_AutoConfigStatus[]= {
	{ 0, "DISABLED" },
	{ 1, "RUNNING" },
	{ 2, "DONE" },
	{ 3, "ERROR" },
	{ 0, NULL }
};


void proto_reg_handoff_op_uavobjects_gpspositionsensor(void);

static int dissect_uavo(tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree)
{
  int offset = 0;

  col_append_str(pinfo->cinfo, COL_INFO, "(GPSPositionSensor)");
		  
  if (tree) { /* we are being asked for details */
    proto_tree *uavo_tree = NULL;
    ptvcursor_t * cursor;
    proto_item *ti = NULL;

    /* Add a top-level entry to the dissector tree for this protocol */
    ti = proto_tree_add_item(tree, proto_uavo, tvb, 0, -1, ENC_NA);

    /* Create a subtree to contain the dissection of this protocol */
    uavo_tree = proto_item_add_subtree(ti, ett_uavo);

    /* Dissect the packet and populate the subtree */
    cursor = ptvcursor_new(uavo_tree, tvb, 0);

    /* Populate the fields in this protocol */
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_Latitude, sizeof(gint32), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_Longitude, sizeof(gint32), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_Altitude, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_GeoidSeparation, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_Heading, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_Groundspeed, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_PDOP, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_HDOP, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_VDOP, sizeof(gfloat), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_Status, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_Satellites, sizeof(gint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_SensorType, sizeof(guint8), ENC_LITTLE_ENDIAN);
    ptvcursor_add(cursor, hf_op_uavobjects_gpspositionsensor_AutoConfigStatus, sizeof(guint8), ENC_LITTLE_ENDIAN);


    offset += ptvcursor_current_offset(cursor);

    ptvcursor_free(cursor);
  } else {
    offset = 0;
  }

  return offset;
}

void proto_register_op_objects_gpspositionsensor(void)
{
   static hf_register_info hf[] = {
	 { &hf_op_uavobjects_gpspositionsensor_Latitude,
	   { "Latitude", "gpspositionsensor.Latitude", FT_INT32,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_Longitude,
	   { "Longitude", "gpspositionsensor.Longitude", FT_INT32,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_Altitude,
	   { "Altitude", "gpspositionsensor.Altitude", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_GeoidSeparation,
	   { "GeoidSeparation", "gpspositionsensor.GeoidSeparation", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_Heading,
	   { "Heading", "gpspositionsensor.Heading", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_Groundspeed,
	   { "Groundspeed", "gpspositionsensor.Groundspeed", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_PDOP,
	   { "PDOP", "gpspositionsensor.PDOP", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_HDOP,
	   { "HDOP", "gpspositionsensor.HDOP", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_VDOP,
	   { "VDOP", "gpspositionsensor.VDOP", FT_FLOAT,
	     BASE_NONE, NULL, 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_Status,
	   { "Status", "gpspositionsensor.Status", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpspositionsensor_Status), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_Satellites,
	   { "Satellites", "gpspositionsensor.Satellites", FT_INT8,
	     BASE_DEC_HEX, NULL, 0x0, NULL, HFILL
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_SensorType,
	   { "SensorType", "gpspositionsensor.SensorType", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpspositionsensor_SensorType), 0x0, NULL, HFILL 
	   },
	 },
	 { &hf_op_uavobjects_gpspositionsensor_AutoConfigStatus,
	   { "AutoConfigStatus", "gpspositionsensor.AutoConfigStatus", FT_UINT8,
	     BASE_DEC, VALS(uavobjects_gpspositionsensor_AutoConfigStatus), 0x0, NULL, HFILL 
	   },
	 },
   };


   /* Setup protocol subtree array */

   static gint *ett[] = {
	&ett_uavo,

   };

   /* Register this protocol */
   proto_uavo = proto_register_protocol("UAVO GPSPositionSensor", 
				   "UAVO GPSPositionSensor", 
				   "uavo-gpspositionsensor");

   /* Register the field definitions for this protocol */
   proto_register_subtree_array(ett, array_length(ett));
   proto_register_field_array(proto_uavo, hf, array_length(hf));
}

void proto_reg_handoff_op_uavobjects_gpspositionsensor(void)
{
   dissector_handle_t uavo_handle;
   uavo_handle = new_create_dissector_handle(dissect_uavo, proto_uavo);

   /* Bind this protocol to its UAV ObjID in UAVTalk */
   dissector_add("uavtalk.objid", 0x7D26A6E6, uavo_handle);
}
