##
##############################################################################
#
# @file       objectpersistence.py
# @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
# @brief      Implementation of the ObjectPersistence object. This file has been
#             automatically generated by the UAVObjectGenerator. For use with
#             the PyMite VM of the FlightPlan module.
#
# @note       Object definition file: objectpersistence.xml.
#             This is an automatically generated file.
#             DO NOT modify manually.
#
# @see        The GNU Public License (GPL) Version 3
#
#############################################################################/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

from uavobject import *

# Field ObjectID definition
class ObjectIDField(UAVObjectField):
    def __init__(self):
        UAVObjectField.__init__(self, 5, 1)

# Field InstanceID definition
class InstanceIDField(UAVObjectField):
    def __init__(self):
        UAVObjectField.__init__(self, 5, 1)

# Field Operation definition
class OperationField(UAVObjectField):
    # Enumeration options
    NOP = 0
    LOAD = 1
    SAVE = 2
    DELETE = 3
    FULLERASE = 4
    COMPLETED = 5
    ERROR = 6
    def __init__(self):
        UAVObjectField.__init__(self, 7, 1)

# Field Selection definition
class SelectionField(UAVObjectField):
    # Enumeration options
    SINGLEOBJECT = 0
    ALLSETTINGS = 1
    ALLMETAOBJECTS = 2
    ALLOBJECTS = 3
    def __init__(self):
        UAVObjectField.__init__(self, 7, 1)



# Object ObjectPersistence definition
class ObjectPersistence(UAVObject):
    # Object constants
    OBJID = -1715064174

    # Constructor
    def __init__(self):
        UAVObject.__init__(self, ObjectPersistence.OBJID)

        # Create object fields
        self.ObjectID = ObjectIDField()
        self.addField(self.ObjectID)
        self.InstanceID = InstanceIDField()
        self.addField(self.InstanceID)
        self.Operation = OperationField()
        self.addField(self.Operation)
        self.Selection = SelectionField()
        self.addField(self.Selection)

        # Read field data
        self.read()
        self.metadata.read()
