##
##############################################################################
#
# @file       systemsettings.py
# @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
# @brief      Implementation of the SystemSettings object. This file has been
#             automatically generated by the UAVObjectGenerator. For use with
#             the PyMite VM of the FlightPlan module.
#
# @note       Object definition file: systemsettings.xml.
#             This is an automatically generated file.
#             DO NOT modify manually.
#
# @see        The GNU Public License (GPL) Version 3
#
#############################################################################/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

from uavobject import *

# Field GUIConfigData definition
class GUIConfigDataField(UAVObjectField):
    def __init__(self):
        UAVObjectField.__init__(self, 5, 4)

# Field AirSpeedMax definition
class AirSpeedMaxField(UAVObjectField):
    def __init__(self):
        UAVObjectField.__init__(self, 6, 1)

# Field AirSpeedMin definition
class AirSpeedMinField(UAVObjectField):
    def __init__(self):
        UAVObjectField.__init__(self, 6, 1)

# Field AirframeType definition
class AirframeTypeField(UAVObjectField):
    # Enumeration options
    FIXEDWING = 0
    FIXEDWINGELEVON = 1
    FIXEDWINGVTAIL = 2
    VTOL = 3
    HELICP = 4
    QUADX = 5
    QUADP = 6
    HEXA = 7
    OCTO = 8
    CUSTOM = 9
    HEXAX = 10
    HEXAH = 11
    OCTOV = 12
    OCTOCOAXP = 13
    OCTOCOAXX = 14
    OCTOX = 15
    HEXACOAX = 16
    TRI = 17
    GROUNDVEHICLECAR = 18
    GROUNDVEHICLEDIFFERENTIAL = 19
    GROUNDVEHICLEMOTORCYCLE = 20
    def __init__(self):
        UAVObjectField.__init__(self, 7, 1)

# Field VehicleName definition
class VehicleNameField(UAVObjectField):
    def __init__(self):
        UAVObjectField.__init__(self, 3, 20)

# Field ThrustControl definition
class ThrustControlField(UAVObjectField):
    # Enumeration options
    THROTTLE = 0
    COLLECTIVE = 1
    NONE = 2
    def __init__(self):
        UAVObjectField.__init__(self, 7, 1)



# Object SystemSettings definition
class SystemSettings(UAVObject):
    # Object constants
    OBJID = -640642120

    # Constructor
    def __init__(self):
        UAVObject.__init__(self, SystemSettings.OBJID)

        # Create object fields
        self.GUIConfigData = GUIConfigDataField()
        self.addField(self.GUIConfigData)
        self.AirSpeedMax = AirSpeedMaxField()
        self.addField(self.AirSpeedMax)
        self.AirSpeedMin = AirSpeedMinField()
        self.addField(self.AirSpeedMin)
        self.AirframeType = AirframeTypeField()
        self.addField(self.AirframeType)
        self.VehicleName = VehicleNameField()
        self.addField(self.VehicleName)
        self.ThrustControl = ThrustControlField()
        self.addField(self.ThrustControl)

        # Read field data
        self.read()
        self.metadata.read()
