#!/usr/bin/env python3
"""Emit Swift UAVObject definitions from shared/uavobjectdefinition/*.xml.

The IDs and the field order are NOT hand-written: they come from pyuavtalk's
own parser, which is the ground-side source of truth (it reproduces
uavobjgenerator's descending-element-size sort and the ID hash). Hand-typing
an object ID is how you get a client that silently receives nothing.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
sys.path.insert(0, os.path.join(REPO, "ground", "pyuavtalk"))
XMLDIR = os.path.join(REPO, "shared", "uavobjectdefinition")

import uavtalk  # noqa: E402
import glob
import xml.etree.ElementTree as ET


def element_names_for(obj_name):
    """Element names per field, e.g. SystemAlarms.Alarm -> [SystemConfiguration, ...].

    pyuavtalk drops these (it only needs counts), but they are exactly what an
    alarm list or a satellite table has to display, so re-read them here.
    """
    for path in glob.glob(os.path.join(XMLDIR, "*.xml")):
        root = ET.parse(path).getroot()
        obj_el = root.find("object")
        if obj_el is None or obj_el.get("name") != obj_name:
            continue
        out = {}
        for field_el in obj_el.findall("field"):
            fname = field_el.get("name")
            names_attr = field_el.get("elementnames")
            if names_attr:
                out[fname] = [n.strip() for n in names_attr.split(",")]
                continue
            names_el = field_el.find("elementnames")
            if names_el is not None:
                got = [n.text for n in names_el.findall("elementname")]
                if got:
                    out[fname] = got
        # resolve cloneof fields to their parent's names
        for field_el in obj_el.findall("field"):
            co = field_el.get("cloneof")
            if co and co in out:
                out[field_el.get("name")] = list(out[co])
        return out
    return {}

WANTED = [
    "SystemAlarms", "AttitudeState", "GPSPositionSensor", "GPSSatellites",
    "GPSTime", "FlightStatus", "ManualControlCommand", "SystemStats",
    "PositionState", "VelocityState", "HomeLocation", "MagState",
    "StabilizationDesired", "ActuatorCommand",
    # write side: sticks, mag calibration, persistence, thresholds
    "GCSReceiver", "RevoCalibration", "ObjectPersistence", "MagSensor",
    "ManualControlSettings", "FlightModeSettings", "RevoSettings",
    # level diagnostics: raw vs calibrated accel, gyro, and the trims that bend them
    "AccelState", "AccelSensor", "GyroState", "AttitudeSettings", "AccelGyroSettings",
]

SWIFT_TYPE = {
    "int8": ".int8", "int16": ".int16", "int32": ".int32",
    "uint8": ".uint8", "uint16": ".uint16", "uint32": ".uint32",
    "float": ".float", "enum": ".enum",
}


def swift_str(s):
    return '"%s"' % s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    db = uavtalk.UAVObjectDB(XMLDIR)
    out = []
    out.append("// Generated by tools/gen_uavobjects.py -- DO NOT EDIT BY HAND.")
    out.append("// Source: shared/uavobjectdefinition/*.xml via ground/pyuavtalk.")
    out.append("// Regenerate after any UAVObject change or the board will")
    out.append("// silently ignore everything this app sends.")
    out.append("")
    out.append("import Foundation")
    out.append("")
    out.append("let uavObjectDefs: [UAVObjectDef] = [")
    for name in WANTED:
        if name not in db:
            sys.stderr.write("WARNING: %s not in XML, skipped\n" % name)
            continue
        d = db[name]
        enames = element_names_for(name)
        out.append("    UAVObjectDef(")
        out.append("        name: %s," % swift_str(d.name))
        out.append("        id: 0x%08X," % d.obj_id)
        out.append("        size: %d," % d.size)
        out.append("        isSingleInstance: %s," % ("true" if d.is_single_instance else "false"))
        out.append("        fields: [")
        for f in d.fields:
            opts = "[]"
            if f.options:
                opts = "[" + ", ".join(swift_str(o) for o in f.options) + "]"
            en = enames.get(f.name)
            enames_swift = "[]"
            if en and len(en) == f.count:
                enames_swift = "[" + ", ".join(swift_str(n) for n in en) + "]"
            out.append("            UAVField(name: %s, type: %s, count: %d, options: %s, elementNames: %s),"
                       % (swift_str(f.name), SWIFT_TYPE[f.type], f.count, opts, enames_swift))
        out.append("        ]),")
    out.append("]")
    out.append("")
    dest = os.path.join(HERE, "..", "NinjaPilotMobile", "Protocol", "UAVObjectDefs.swift")
    with open(os.path.abspath(dest), "w") as fh:
        fh.write("\n".join(out))
    print("wrote %s" % os.path.abspath(dest))
    for name in WANTED:
        if name in db:
            print("  %-22s id=0x%08X size=%d fields=%d"
                  % (name, db[name].obj_id, db[name].size, len(db[name].fields)))


if __name__ == "__main__":
    main()
